"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "hi" | "ml";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>("en");

    useEffect(() => {
        const stored = localStorage.getItem("app-language") as Language | null;
        if (stored && ["en", "hi", "ml"].includes(stored)) {
            setLanguageState(stored);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("app-language", lang);
    };

    const t = (key: string): string => {
        const trans = translations[language];
        const keys = key.split(".");
        let result: any = trans;
        for (const k of keys) {
            result = result?.[k];
        }
        if (typeof result === "string") return result;
        // Fallback to English
        let fallback: any = translations["en"];
        for (const k of keys) {
            fallback = fallback?.[k];
        }
        return typeof fallback === "string" ? fallback : key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
    return ctx;
}

// ─── Translations ─────────────────────────────────────────────────────────────

const translations: Record<Language, Record<string, any>> = {
    en: {
        // Common
        common: {
            loading: "Loading...",
            save: "Save",
            cancel: "Cancel",
            delete: "Delete",
            edit: "Edit",
            create: "Create",
            submit: "Submit",
            close: "Close",
            confirm: "Confirm",
            search: "Search",
            filter: "Filter",
            sort: "Sort",
            refresh: "Refresh",
            viewAll: "View All",
            showLess: "Show Less",
            noData: "No data found",
            error: "Error",
            success: "Success",
            status: "Status",
            date: "Date",
            amount: "Amount",
            quantity: "Quantity",
            price: "Price",
            name: "Name",
            description: "Description",
            category: "Category",
            all: "All",
            actions: "Actions",
            details: "Details",
            message: "Message",
            notes: "Notes",
            signOut: "Sign out",
            myAccount: "My Account",
            settings: "Settings",
            welcome: "Welcome",
        },
        // Layout / Navigation
        layout: {
            buyerDashboard: "Buyer Dashboard",
            sellerDashboard: "Seller Dashboard",
            shippingDashboard: "Shipping Provider Dashboard",
            adminDashboard: "Admin Dashboard",
            browseItems: "Browse Items",
            myBidRequests: "My Bid Requests",
            sellerBids: "Seller Bids",
            cardamomPrices: "Cardamom Prices",
            dashboard: "Dashboard",
            buyerOrders: "Buyer Orders",
            myBids: "My Bids",
            availableOrders: "Available Orders",
            myShippingBids: "My Shipping Bids",
            overview: "Overview",
            manageItems: "Manage Items",
            manageOrders: "Manage Orders",
            users: "Users",
            rfqs: "RFQs",
            marketPrices: "Market Prices",
        },
        // Status labels
        status: {
            pending: "Pending",
            accepted: "Accepted",
            rejected: "Rejected",
            completed: "Completed",
            cancelled: "Cancelled",
            active: "Active",
            inactive: "Inactive",
            open: "Open",
            closed: "Closed",
            draft: "Draft",
            awarded: "Awarded",
            sold: "Sold",
        },
        // Buyer Dashboard
        buyer: {
            pageTitle: "Buyer Dashboard",
            browseItems: "Browse Items",
            myOrders: "My Bid Requests",
            sellerBids: "Seller Bids",
            stats: {
                totalOrders: "Total Orders",
                pendingBids: "Pending Bids",
                acceptedBids: "Accepted Bids",
                totalSpent: "Total Spent",
                activeOrders: "Active Orders",
                completedOrders: "Completed",
            },
            createOrder: "Create Bid Request",
            newOrder: "New Bid Request",
            placeOrder: "Place Order",
            selectProduct: "Select Product",
            quantity: "Quantity (kg)",
            deliveryAddress: "Delivery Address",
            specialInstructions: "Special Instructions",
            bidDeadline: "Bid Deadline",
            orderPlaced: "Order placed successfully!",
            orderFailed: "Failed to place order",
            noItems: "No items available",
            noBids: "No bids yet",
            noOrders: "No orders yet",
            acceptBid: "Accept Bid",
            rejectBid: "Reject Bid",
            viewBids: "View Bids",
            orderDetails: "Order Details",
            bidDetails: "Bid Details",
            estimatedDelivery: "Estimated Delivery",
            bidAmount: "Bid Amount",
            sellerName: "Seller",
            timeRemaining: "Time Remaining",
            expired: "Expired",
            lowestBid: "Lowest Bid",
            highestBid: "Highest Bid",
            acceptedBid: "Accepted Bid",
            shippingBids: "Shipping Bids",
            deliveryBid: "Delivery Bid",
            acceptShipping: "Accept Shipping",
            totalBids: "Total Bids",
            analytics: "Analytics",
            recentOrders: "Recent Orders",
            searchPlaceholder: "Search products...",
            filterByCategory: "Filter by category",
            sortBy: "Sort by",
            congratulations: "Congratulations!",
            bidAccepted: "Bid accepted successfully",
        },
        // Seller Dashboard
        seller: {
            pageTitle: "Seller Dashboard",
            stats: {
                totalOrders: "Total Orders",
                pendingBids: "Pending Bids",
                acceptedBids: "Accepted Bids",
                rejectedBids: "Rejected Bids",
                totalRevenue: "Total Revenue",
                potentialRevenue: "Potential Revenue",
            },
            buyerOrders: "Buyer Orders",
            myBids: "My Bids",
            submitBid: "Submit Bid",
            updateBid: "Update Bid",
            bidAmount: "Bid Amount (₹/kg)",
            estimatedDelivery: "Estimated Delivery Date",
            pickupAddress: "Pickup Address",
            message: "Message to Buyer",
            noBids: "No bids submitted yet",
            noOrders: "No buyer orders available",
            bidSubmitted: "Bid submitted successfully",
            bidUpdated: "Bid updated successfully",
            analytics: "Analytics",
            revenueOverview: "Revenue Overview",
            bidStatus: "Bid Status",
            searchOrders: "Search orders...",
            searchBids: "Search bids...",
            filterStatus: "Filter by status",
            yourBid: "Your bid",
            competingBids: "other bids",
            lowestBid: "Lowest bid so far",
            youAreLowest: "You are the lowest bidder!",
        },
        // Admin Dashboard
        admin: {
            pageTitle: "Admin Dashboard",
            stats: {
                totalItems: "Total Items",
                totalOrders: "Total Orders",
                totalBids: "Total Bids",
                totalUsers: "Total Users",
                activeItems: "Active Items",
                pendingOrders: "Pending Orders",
                totalRevenue: "Total Revenue",
            },
            addItem: "Add Item",
            editItem: "Edit Item",
            deleteItem: "Delete Item",
            addSeller: "Add Seller",
            manageItems: "Manage Items",
            manageOrders: "Manage Orders",
            manageUsers: "Users",
            confirmDelete: "Are you sure you want to delete this item?",
            itemName: "Item Name",
            itemDescription: "Description",
            itemPrice: "Price",
            itemCategory: "Category",
            itemQuantity: "Quantity",
            itemCondition: "Condition",
            specifications: "Specifications",
            addSpec: "Add Specification",
            sellerEmail: "Seller Email",
            sellerName: "Seller Name",
            sellerPassword: "Password",
            createSellerAccount: "Create Seller Account",
        },
        // Shipping Provider Dashboard
        shipping: {
            pageTitle: "Shipping Provider Dashboard",
            stats: {
                totalOrders: "Available Orders",
                pendingBids: "Pending Bids",
                acceptedBids: "Accepted Bids",
                rejectedBids: "Rejected Bids",
                potentialRevenue: "Potential Revenue",
                totalBidValue: "Total Bid Value",
            },
            availableOrders: "Available Orders",
            myBids: "My Shipping Bids",
            submitBid: "Submit Bid",
            updateBid: "Update Bid",
            bidAmount: "Bid Amount (₹)",
            estimatedDelivery: "Estimated Delivery Date",
            message: "Message",
            noBids: "No shipping bids submitted yet",
            noOrders: "No orders available for shipping",
            bidSubmitted: "Shipping bid submitted",
            bidUpdated: "Shipping bid updated",
            pickupAddress: "Pickup Address",
            deliveryAddress: "Delivery Address",
            distance: "Distance",
            analytics: "Analytics",
        },
        // Cardamom Prices
        cardamom: {
            pageTitle: "Cardamom Market Prices",
            liveData: "Live Market Data",
            lastUpdated: "Last Updated",
            grade: "Grade",
            minPrice: "Min Price",
            maxPrice: "Max Price",
            modalPrice: "Modal Price",
            market: "Market",
            commodity: "Commodity",
            variety: "Variety",
            noData: "No price data available",
            refreshData: "Refresh Data",
        },
        // RFQ Management
        rfq: {
            pageTitle: "RFQ Management",
            createRFQ: "Create New RFQ",
            myRFQs: "My RFQs",
            totalRFQs: "Total RFQs",
            openRFQs: "Open RFQs",
            awarded: "Awarded",
            totalQuotes: "Total Quotes",
            rfqTitle: "RFQ Title",
            rfqDescription: "Description",
            deadline: "Deadline",
            viewDetails: "View Details",
            noRFQs: "No RFQs found",
            manageQuotes: "Manage your Request for Quotes",
        },
        // Market Prices
        market: {
            pageTitle: "Market Prices",
            liveUpdates: "Live Updates",
            historicalData: "Historical Data",
        },
    },

    // ─── Hindi ─────────────────────────────────────────────────────────────────
    hi: {
        common: {
            loading: "लोड हो रहा है...",
            save: "सहेजें",
            cancel: "रद्द करें",
            delete: "हटाएं",
            edit: "संपादित करें",
            create: "बनाएं",
            submit: "जमा करें",
            close: "बंद करें",
            confirm: "पुष्टि करें",
            search: "खोजें",
            filter: "फ़िल्टर",
            sort: "क्रमबद्ध करें",
            refresh: "ताज़ा करें",
            viewAll: "सभी देखें",
            showLess: "कम दिखाएं",
            noData: "कोई डेटा नहीं मिला",
            error: "त्रुटि",
            success: "सफलता",
            status: "स्थिति",
            date: "तारीख",
            amount: "राशि",
            quantity: "मात्रा",
            price: "मूल्य",
            name: "नाम",
            description: "विवरण",
            category: "श्रेणी",
            all: "सभी",
            actions: "क्रियाएं",
            details: "विवरण",
            message: "संदेश",
            notes: "नोट्स",
            signOut: "साइन आउट",
            myAccount: "मेरा खाता",
            settings: "सेटिंग्स",
            welcome: "स्वागत है",
        },
        layout: {
            buyerDashboard: "खरीदार डैशबोर्ड",
            sellerDashboard: "विक्रेता डैशबोर्ड",
            shippingDashboard: "शिपिंग प्रदाता डैशबोर्ड",
            adminDashboard: "व्यवस्थापक डैशबोर्ड",
            browseItems: "उत्पाद देखें",
            myBidRequests: "मेरी बोली अनुरोध",
            sellerBids: "विक्रेता बोलियां",
            cardamomPrices: "इलायची भाव",
            dashboard: "डैशबोर्ड",
            buyerOrders: "खरीदार ऑर्डर",
            myBids: "मेरी बोलियां",
            availableOrders: "उपलब्ध ऑर्डर",
            myShippingBids: "मेरी शिपिंग बोलियां",
            overview: "अवलोकन",
            manageItems: "उत्पाद प्रबंधन",
            manageOrders: "ऑर्डर प्रबंधन",
            users: "उपयोगकर्ता",
            rfqs: "आरएफक्यू",
            marketPrices: "बाज़ार भाव",
        },
        status: {
            pending: "लंबित",
            accepted: "स्वीकृत",
            rejected: "अस्वीकृत",
            completed: "पूर्ण",
            cancelled: "रद्द",
            active: "सक्रिय",
            inactive: "निष्क्रिय",
            open: "खुला",
            closed: "बंद",
            draft: "मसौदा",
            awarded: "पुरस्कृत",
            sold: "बेचा गया",
        },
        buyer: {
            pageTitle: "खरीदार डैशबोर्ड",
            browseItems: "उत्पाद देखें",
            myOrders: "मेरी बोली अनुरोध",
            sellerBids: "विक्रेता बोलियां",
            stats: {
                totalOrders: "कुल ऑर्डर",
                pendingBids: "लंबित बोलियां",
                acceptedBids: "स्वीकृत बोलियां",
                totalSpent: "कुल खर्च",
                activeOrders: "सक्रिय ऑर्डर",
                completedOrders: "पूर्ण",
            },
            createOrder: "बोली अनुरोध बनाएं",
            newOrder: "नया बोली अनुरोध",
            placeOrder: "ऑर्डर दें",
            selectProduct: "उत्पाद चुनें",
            quantity: "मात्रा (किग्रा)",
            deliveryAddress: "डिलीवरी पता",
            specialInstructions: "विशेष निर्देश",
            bidDeadline: "बोली की समय सीमा",
            orderPlaced: "ऑर्डर सफलतापूर्वक दिया गया!",
            orderFailed: "ऑर्डर देने में विफल",
            noItems: "कोई उत्पाद उपलब्ध नहीं",
            noBids: "अभी तक कोई बोली नहीं",
            noOrders: "अभी तक कोई ऑर्डर नहीं",
            acceptBid: "बोली स्वीकार करें",
            rejectBid: "बोली अस्वीकार करें",
            viewBids: "बोलियां देखें",
            orderDetails: "ऑर्डर विवरण",
            bidDetails: "बोली विवरण",
            estimatedDelivery: "अनुमानित डिलीवरी",
            bidAmount: "बोली राशि",
            sellerName: "विक्रेता",
            timeRemaining: "शेष समय",
            expired: "समाप्त",
            lowestBid: "सबसे कम बोली",
            highestBid: "सबसे अधिक बोली",
            acceptedBid: "स्वीकृत बोली",
            shippingBids: "शिपिंग बोलियां",
            deliveryBid: "डिलीवरी बोली",
            acceptShipping: "शिपिंग स्वीकार करें",
            totalBids: "कुल बोलियां",
            analytics: "विश्लेषण",
            recentOrders: "हाल के ऑर्डर",
            searchPlaceholder: "उत्पाद खोजें...",
            filterByCategory: "श्रेणी के अनुसार फ़िल्टर",
            sortBy: "क्रमबद्ध करें",
            congratulations: "बधाई!",
            bidAccepted: "बोली सफलतापूर्वक स्वीकार की गई",
        },
        seller: {
            pageTitle: "विक्रेता डैशबोर्ड",
            stats: {
                totalOrders: "कुल ऑर्डर",
                pendingBids: "लंबित बोलियां",
                acceptedBids: "स्वीकृत बोलियां",
                rejectedBids: "अस्वीकृत बोलियां",
                totalRevenue: "कुल राजस्व",
                potentialRevenue: "संभावित राजस्व",
            },
            buyerOrders: "खरीदार ऑर्डर",
            myBids: "मेरी बोलियां",
            submitBid: "बोली जमा करें",
            updateBid: "बोली अपडेट करें",
            bidAmount: "बोली राशि (₹/किग्रा)",
            estimatedDelivery: "अनुमानित डिलीवरी तारीख",
            pickupAddress: "पिकअप पता",
            message: "खरीदार को संदेश",
            noBids: "अभी तक कोई बोली जमा नहीं",
            noOrders: "कोई खरीदार ऑर्डर उपलब्ध नहीं",
            bidSubmitted: "बोली सफलतापूर्वक जमा की गई",
            bidUpdated: "बोली सफलतापूर्वक अपडेट की गई",
            analytics: "विश्लेषण",
            revenueOverview: "राजस्व अवलोकन",
            bidStatus: "बोली स्थिति",
            searchOrders: "ऑर्डर खोजें...",
            searchBids: "बोलियां खोजें...",
            filterStatus: "स्थिति के अनुसार फ़िल्टर",
            yourBid: "आपकी बोली",
            competingBids: "अन्य बोलियां",
            lowestBid: "अब तक की सबसे कम बोली",
            youAreLowest: "आप सबसे कम बोली लगाने वाले हैं!",
        },
        admin: {
            pageTitle: "व्यवस्थापक डैशबोर्ड",
            stats: {
                totalItems: "कुल उत्पाद",
                totalOrders: "कुल ऑर्डर",
                totalBids: "कुल बोलियां",
                totalUsers: "कुल उपयोगकर्ता",
                activeItems: "सक्रिय उत्पाद",
                pendingOrders: "लंबित ऑर्डर",
                totalRevenue: "कुल राजस्व",
            },
            addItem: "उत्पाद जोड़ें",
            editItem: "उत्पाद संपादित करें",
            deleteItem: "उत्पाद हटाएं",
            addSeller: "विक्रेता जोड़ें",
            manageItems: "उत्पाद प्रबंधन",
            manageOrders: "ऑर्डर प्रबंधन",
            manageUsers: "उपयोगकर्ता",
            confirmDelete: "क्या आप इस उत्पाद को हटाना चाहते हैं?",
            itemName: "उत्पाद नाम",
            itemDescription: "विवरण",
            itemPrice: "मूल्य",
            itemCategory: "श्रेणी",
            itemQuantity: "मात्रा",
            itemCondition: "स्थिति",
            specifications: "विनिर्देश",
            addSpec: "विनिर्देश जोड़ें",
            sellerEmail: "विक्रेता ईमेल",
            sellerName: "विक्रेता नाम",
            sellerPassword: "पासवर्ड",
            createSellerAccount: "विक्रेता खाता बनाएं",
        },
        shipping: {
            pageTitle: "शिपिंग प्रदाता डैशबोर्ड",
            stats: {
                totalOrders: "उपलब्ध ऑर्डर",
                pendingBids: "लंबित बोलियां",
                acceptedBids: "स्वीकृत बोलियां",
                rejectedBids: "अस्वीकृत बोलियां",
                potentialRevenue: "संभावित राजस्व",
                totalBidValue: "कुल बोली मूल्य",
            },
            availableOrders: "उपलब्ध ऑर्डर",
            myBids: "मेरी शिपिंग बोलियां",
            submitBid: "बोली जमा करें",
            updateBid: "बोली अपडेट करें",
            bidAmount: "बोली राशि (₹)",
            estimatedDelivery: "अनुमानित डिलीवरी तारीख",
            message: "संदेश",
            noBids: "अभी तक कोई शिपिंग बोली जमा नहीं",
            noOrders: "शिपिंग के लिए कोई ऑर्डर उपलब्ध नहीं",
            bidSubmitted: "शिपिंग बोली जमा की गई",
            bidUpdated: "शिपिंग बोली अपडेट की गई",
            pickupAddress: "पिकअप पता",
            deliveryAddress: "डिलीवरी पता",
            distance: "दूरी",
            analytics: "विश्लेषण",
        },
        cardamom: {
            pageTitle: "इलायची बाज़ार भाव",
            liveData: "लाइव बाज़ार डेटा",
            lastUpdated: "अंतिम अपडेट",
            grade: "ग्रेड",
            minPrice: "न्यूनतम मूल्य",
            maxPrice: "अधिकतम मूल्य",
            modalPrice: "मोडल मूल्य",
            market: "बाज़ार",
            commodity: "वस्तु",
            variety: "किस्म",
            noData: "कोई मूल्य डेटा उपलब्ध नहीं",
            refreshData: "डेटा ताज़ा करें",
        },
        rfq: {
            pageTitle: "आरएफक्यू प्रबंधन",
            createRFQ: "नया आरएफक्यू बनाएं",
            myRFQs: "मेरे आरएफक्यू",
            totalRFQs: "कुल आरएफक्यू",
            openRFQs: "खुले आरएफक्यू",
            awarded: "पुरस्कृत",
            totalQuotes: "कुल कोटेशन",
            rfqTitle: "आरएफक्यू शीर्षक",
            rfqDescription: "विवरण",
            deadline: "समय सीमा",
            viewDetails: "विवरण देखें",
            noRFQs: "कोई आरएफक्यू नहीं मिला",
            manageQuotes: "अपने कोटेशन अनुरोध प्रबंधित करें",
        },
        market: {
            pageTitle: "बाज़ार भाव",
            liveUpdates: "लाइव अपडेट",
            historicalData: "ऐतिहासिक डेटा",
        },
    },

    // ─── Malayalam ─────────────────────────────────────────────────────────────
    ml: {
        common: {
            loading: "ലോഡ് ചെയ്യുന്നു...",
            save: "സേവ് ചെയ്യുക",
            cancel: "റദ്ദാക്കുക",
            delete: "ഇല്ലാതാക്കുക",
            edit: "എഡിറ്റ് ചെയ്യുക",
            create: "സൃഷ്ടിക്കുക",
            submit: "സമർപ്പിക്കുക",
            close: "അടയ്ക്കുക",
            confirm: "സ്ഥിരീകരിക്കുക",
            search: "തിരയുക",
            filter: "ഫിൽറ്റർ",
            sort: "അടുക്കുക",
            refresh: "പുതുക്കുക",
            viewAll: "എല്ലാം കാണുക",
            showLess: "കുറവ് കാണിക്കുക",
            noData: "ഡാറ്റ കണ്ടെത്തിയില്ല",
            error: "പിശക്",
            success: "വിജയം",
            status: "നില",
            date: "തീയതി",
            amount: "തുക",
            quantity: "അളവ്",
            price: "വില",
            name: "പേര്",
            description: "വിവരണം",
            category: "വിഭാഗം",
            all: "എല്ലാം",
            actions: "പ്രവർത്തനങ്ങൾ",
            details: "വിശദാംശങ്ങൾ",
            message: "സന്ദേശം",
            notes: "കുറിപ്പുകൾ",
            signOut: "സൈൻ ഔട്ട്",
            myAccount: "എന്റെ അക്കൗണ്ട്",
            settings: "ക്രമീകരണങ്ങൾ",
            welcome: "സ്വാഗതം",
        },
        layout: {
            buyerDashboard: "വാങ്ങുന്നവരുടെ ഡാഷ്ബോർഡ്",
            sellerDashboard: "വിൽക്കുന്നവരുടെ ഡാഷ്ബോർഡ്",
            shippingDashboard: "ഷിപ്പിംഗ് ദാതാവ് ഡാഷ്ബോർഡ്",
            adminDashboard: "അഡ്മിൻ ഡാഷ്ബോർഡ്",
            browseItems: "ഉൽപ്പന്നങ്ങൾ കാണുക",
            myBidRequests: "എന്റെ ബിഡ് അഭ്യർഥനകൾ",
            sellerBids: "വിൽക്കുന്നവരുടെ ബിഡ്ഡുകൾ",
            cardamomPrices: "ഏലം വില",
            dashboard: "ഡാഷ്ബോർഡ്",
            buyerOrders: "വാങ്ങുന്നവരുടെ ഓർഡറുകൾ",
            myBids: "എന്റെ ബിഡ്ഡുകൾ",
            availableOrders: "ലഭ്യമായ ഓർഡറുകൾ",
            myShippingBids: "എന്റെ ഷിപ്പിംഗ് ബിഡ്ഡുകൾ",
            overview: "അവലോകനം",
            manageItems: "ഉൽപ്പന്ന മാനേജ്‌മെന്റ്",
            manageOrders: "ഓർഡർ മാനേജ്‌മെന്റ്",
            users: "ഉപയോക്താക്കൾ",
            rfqs: "ആർഎഫ്ക്യു",
            marketPrices: "മാർക്കറ്റ് വില",
        },
        status: {
            pending: "പരിഗണനയിൽ",
            accepted: "സ്വീകരിച്ചു",
            rejected: "നിരസിച്ചു",
            completed: "പൂർത്തിയായി",
            cancelled: "റദ്ദാക്കി",
            active: "സജീവം",
            inactive: "നിഷ്ക്രിയം",
            open: "തുറന്നിരിക്കുന്നു",
            closed: "അടഞ്ഞിരിക്കുന്നു",
            draft: "ഡ്രാഫ്റ്റ്",
            awarded: "അവാർഡ് ചെയ്തു",
            sold: "വിറ്റു",
        },
        buyer: {
            pageTitle: "വാങ്ങുന്നവരുടെ ഡാഷ്ബോർഡ്",
            browseItems: "ഉൽപ്പന്നങ്ങൾ കാണുക",
            myOrders: "എന്റെ ബിഡ് അഭ്യർഥനകൾ",
            sellerBids: "വിൽക്കുന്നവരുടെ ബിഡ്ഡുകൾ",
            stats: {
                totalOrders: "മൊത്തം ഓർഡറുകൾ",
                pendingBids: "കാത്തിരിക്കുന്ന ബിഡ്ഡുകൾ",
                acceptedBids: "സ്വീകരിച്ച ബിഡ്ഡുകൾ",
                totalSpent: "മൊത്തം ചെലവ്",
                activeOrders: "സജീവ ഓർഡറുകൾ",
                completedOrders: "പൂർത്തിയായവ",
            },
            createOrder: "ബിഡ് അഭ്യർഥന സൃഷ്ടിക്കുക",
            newOrder: "പുതിയ ബിഡ് അഭ്യർഥന",
            placeOrder: "ഓർഡർ നൽകുക",
            selectProduct: "ഉൽപ്പന്നം തിരഞ്ഞെടുക്കുക",
            quantity: "അളവ് (കി.ഗ്രാം)",
            deliveryAddress: "ഡെലിവറി വിലാസം",
            specialInstructions: "പ്രത്യേക നിർദ്ദേശങ്ങൾ",
            bidDeadline: "ബിഡ് സമയ പരിധി",
            orderPlaced: "ഓർഡർ വിജയകരമായി നൽകി!",
            orderFailed: "ഓർഡർ നൽകുന്നതിൽ പരാജയം",
            noItems: "ഉൽപ്പന്നങ്ങൾ ലഭ്യമല്ല",
            noBids: "ഇതുവരെ ബിഡ്ഡുകൾ ഇല്ല",
            noOrders: "ഇതുവരെ ഓർഡറുകൾ ഇല്ല",
            acceptBid: "ബിഡ് സ്വീകരിക്കുക",
            rejectBid: "ബിഡ് നിരസിക്കുക",
            viewBids: "ബിഡ്ഡുകൾ കാണുക",
            orderDetails: "ഓർഡർ വിശദാംശങ്ങൾ",
            bidDetails: "ബിഡ് വിശദാംശങ്ങൾ",
            estimatedDelivery: "ഏകദേശ ഡെലിവറി",
            bidAmount: "ബിഡ് തുക",
            sellerName: "വിൽക്കുന്നയാൾ",
            timeRemaining: "ശേഷിക്കുന്ന സമയം",
            expired: "കാലഹരണപ്പെട്ടു",
            lowestBid: "ഏറ്റവും കുറഞ്ഞ ബിഡ്",
            highestBid: "ഏറ്റവും ഉയർന്ന ബിഡ്",
            acceptedBid: "സ്വീകരിച്ച ബിഡ്",
            shippingBids: "ഷിപ്പിംഗ് ബിഡ്ഡുകൾ",
            deliveryBid: "ഡെലിവറി ബിഡ്",
            acceptShipping: "ഷിപ്പിംഗ് സ്വീകരിക്കുക",
            totalBids: "മൊത്തം ബിഡ്ഡുകൾ",
            analytics: "വിശകലനം",
            recentOrders: "സമീപകാല ഓർഡറുകൾ",
            searchPlaceholder: "ഉൽപ്പന്നങ്ങൾ തിരയുക...",
            filterByCategory: "വിഭാഗം അനുസരിച്ച് ഫിൽറ്റർ ചെയ്യുക",
            sortBy: "അടുക്കുക",
            congratulations: "അഭിനന്ദനങ്ങൾ!",
            bidAccepted: "ബിഡ് വിജയകരമായി സ്വീകരിച്ചു",
        },
        seller: {
            pageTitle: "വിൽക്കുന്നവരുടെ ഡാഷ്ബോർഡ്",
            stats: {
                totalOrders: "മൊത്തം ഓർഡറുകൾ",
                pendingBids: "കാത്തിരിക്കുന്ന ബിഡ്ഡുകൾ",
                acceptedBids: "സ്വീകരിച്ച ബിഡ്ഡുകൾ",
                rejectedBids: "നിരസിച്ച ബിഡ്ഡുകൾ",
                totalRevenue: "മൊത്തം വരുമാനം",
                potentialRevenue: "സാധ്യതാ വരുമാനം",
            },
            buyerOrders: "വാങ്ങുന്നവരുടെ ഓർഡറുകൾ",
            myBids: "എന്റെ ബിഡ്ഡുകൾ",
            submitBid: "ബിഡ് സമർപ്പിക്കുക",
            updateBid: "ബിഡ് അപ്‌ഡേറ്റ് ചെയ്യുക",
            bidAmount: "ബിഡ് തുക (₹/കി.ഗ്രാം)",
            estimatedDelivery: "ഏകദേശ ഡെലിവറി തീയതി",
            pickupAddress: "പിക്കപ്പ് വിലാസം",
            message: "വാങ്ങുന്നവർക്കുള്ള സന്ദേശം",
            noBids: "ഇതുവരെ ബിഡ്ഡുകൾ സമർപ്പിച്ചിട്ടില്ല",
            noOrders: "വാങ്ങുന്നവരുടെ ഓർഡറുകൾ ലഭ്യമല്ല",
            bidSubmitted: "ബിഡ് വിജയകരമായി സമർപ്പിച്ചു",
            bidUpdated: "ബിഡ് വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു",
            analytics: "വിശകലനം",
            revenueOverview: "വരുമാന അവലോകനം",
            bidStatus: "ബിഡ് നില",
            searchOrders: "ഓർഡറുകൾ തിരയുക...",
            searchBids: "ബിഡ്ഡുകൾ തിരയുക...",
            filterStatus: "നില അനുസരിച്ച് ഫിൽറ്റർ ചെയ്യുക",
            yourBid: "നിങ്ങളുടെ ബിഡ്",
            competingBids: "മറ്റ് ബിഡ്ഡുകൾ",
            lowestBid: "ഇതുവരെ ഏറ്റവും കുറഞ്ഞ ബിഡ്",
            youAreLowest: "നിങ്ങൾ ഏറ്റവും കുറഞ്ഞ ബിഡ്ദർ ആണ്!",
        },
        admin: {
            pageTitle: "അഡ്മിൻ ഡാഷ്ബോർഡ്",
            stats: {
                totalItems: "മൊത്തം ഉൽപ്പന്നങ്ങൾ",
                totalOrders: "മൊത്തം ഓർഡറുകൾ",
                totalBids: "മൊത്തം ബിഡ്ഡുകൾ",
                totalUsers: "മൊത്തം ഉപയോക്താക്കൾ",
                activeItems: "സജീവ ഉൽപ്പന്നങ്ങൾ",
                pendingOrders: "കാത്തിരിക്കുന്ന ഓർഡറുകൾ",
                totalRevenue: "മൊത്തം വരുമാനം",
            },
            addItem: "ഉൽപ്പന്നം ചേർക്കുക",
            editItem: "ഉൽപ്പന്നം എഡിറ്റ് ചെയ്യുക",
            deleteItem: "ഉൽപ്പന്നം ഇല്ലാതാക്കുക",
            addSeller: "വിൽക്കുന്നയാളെ ചേർക്കുക",
            manageItems: "ഉൽപ്പന്ന മാനേജ്‌മെന്റ്",
            manageOrders: "ഓർഡർ മാനേജ്‌മെന്റ്",
            manageUsers: "ഉപയോക്താക്കൾ",
            confirmDelete: "ഈ ഉൽപ്പന്നം ഇല്ലാതാക്കണമോ?",
            itemName: "ഉൽപ്പന്നത്തിന്റെ പേര്",
            itemDescription: "വിവരണം",
            itemPrice: "വില",
            itemCategory: "വിഭാഗം",
            itemQuantity: "അളവ്",
            itemCondition: "അവസ്ഥ",
            specifications: "സ്പെസിഫിക്കേഷനുകൾ",
            addSpec: "സ്പെസിഫിക്കേഷൻ ചേർക്കുക",
            sellerEmail: "വിൽക്കുന്നയാളുടെ ഇമെയിൽ",
            sellerName: "വിൽക്കുന്നയാളുടെ പേര്",
            sellerPassword: "പാസ്‌വേഡ്",
            createSellerAccount: "വിൽക്കുന്നയാളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക",
        },
        shipping: {
            pageTitle: "ഷിപ്പിംഗ് ദാതാവ് ഡാഷ്ബോർഡ്",
            stats: {
                totalOrders: "ലഭ്യമായ ഓർഡറുകൾ",
                pendingBids: "കാത്തിരിക്കുന്ന ബിഡ്ഡുകൾ",
                acceptedBids: "സ്വീകരിച്ച ബിഡ്ഡുകൾ",
                rejectedBids: "നിരസിച്ച ബിഡ്ഡുകൾ",
                potentialRevenue: "സാധ്യതാ വരുമാനം",
                totalBidValue: "മൊത്തം ബിഡ് മൂല്യം",
            },
            availableOrders: "ലഭ്യമായ ഓർഡറുകൾ",
            myBids: "എന്റെ ഷിപ്പിംഗ് ബിഡ്ഡുകൾ",
            submitBid: "ബിഡ് സമർപ്പിക്കുക",
            updateBid: "ബിഡ് അപ്‌ഡേറ്റ് ചെയ്യുക",
            bidAmount: "ബിഡ് തുക (₹)",
            estimatedDelivery: "ഏകദേശ ഡെലിവറി തീയതി",
            message: "സന്ദേശം",
            noBids: "ഇതുവരെ ഷിപ്പിംഗ് ബിഡ്ഡുകൾ സമർപ്പിച്ചിട്ടില്ല",
            noOrders: "ഷിപ്പിംഗിനായി ഓർഡറുകൾ ലഭ്യമല്ല",
            bidSubmitted: "ഷിപ്പിംഗ് ബിഡ് സമർപ്പിച്ചു",
            bidUpdated: "ഷിപ്പിംഗ് ബിഡ് അപ്‌ഡേറ്റ് ചെയ്തു",
            pickupAddress: "പിക്കപ്പ് വിലാസം",
            deliveryAddress: "ഡെലിവറി വിലാസം",
            distance: "ദൂരം",
            analytics: "വിശകലനം",
        },
        cardamom: {
            pageTitle: "ഏലം മാർക്കറ്റ് വില",
            liveData: "തൽസമയ മാർക്കറ്റ് ഡാറ്റ",
            lastUpdated: "അവസാനം അപ്‌ഡേറ്റ് ചെയ്തത്",
            grade: "ഗ്രേഡ്",
            minPrice: "കുറഞ്ഞ വില",
            maxPrice: "ഉയർന്ന വില",
            modalPrice: "മോഡൽ വില",
            market: "മാർക്കറ്റ്",
            commodity: "ചരക്ക്",
            variety: "ഇനം",
            noData: "വില ഡാറ്റ ലഭ്യമല്ല",
            refreshData: "ഡാറ്റ പുതുക്കുക",
        },
        rfq: {
            pageTitle: "ആർഎഫ്ക്യു മാനേജ്‌മെന്റ്",
            createRFQ: "പുതിയ ആർഎഫ്ക്യു സൃഷ്ടിക്കുക",
            myRFQs: "എന്റെ ആർഎഫ്ക്യുകൾ",
            totalRFQs: "മൊത്തം ആർഎഫ്ക്യുകൾ",
            openRFQs: "തുറന്ന ആർഎഫ്ക്യുകൾ",
            awarded: "അവാർഡ് ചെയ്തത്",
            totalQuotes: "മൊത്തം ക്വോട്ടുകൾ",
            rfqTitle: "ആർഎഫ്ക്യു തലക്കെട്ട്",
            rfqDescription: "വിശദാംശം",
            deadline: "സമയ പരിധി",
            viewDetails: "വിശദാംശങ്ങൾ കാണുക",
            noRFQs: "ആർഎഫ്ക്യുകൾ ഇല്ല",
            manageQuotes: "നിങ്ങളുടെ ക്വോട്ട് അഭ്യർഥനകൾ നിയന്ത്രിക്കുക",
        },
        market: {
            pageTitle: "മാർക്കറ്റ് വില",
            liveUpdates: "തൽസമയ അപ്‌ഡേറ്റ്",
            historicalData: "ചരിത്ര ഡാറ്റ",
        },
    },
};
