"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "hi" | "ml";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>("en");

    useEffect(() => {
        const stored = localStorage.getItem("app-language") as Language | null;
        if (stored && ["en", "hi", "ml"].includes(stored)) {
            setLanguageState(stored);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("app-language", lang);
    };

    const t = (key: string): string => {
        const trans = translations[language];
        const keys = key.split(".");
        let result: any = trans;
        for (const k of keys) {
            result = result?.[k];
        }
        if (typeof result === "string") return result;
        // Fallback to English
        let fallback: any = translations["en"];
        for (const k of keys) {
            fallback = fallback?.[k];
        }
        return typeof fallback === "string" ? fallback : key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
    return ctx;
}

// ─── Translations ─────────────────────────────────────────────────────────────

const translations: Record<Language, Record<string, any>> = {
    en: {
        // Common
        common: {
            loading: "Loading...",
            save: "Save",
            cancel: "Cancel",
            delete: "Delete",
            edit: "Edit",
            create: "Create",
            submit: "Submit",
            close: "Close",
            confirm: "Confirm",
            search: "Search",
            filter: "Filter",
            sort: "Sort",
            refresh: "Refresh",
            viewAll: "View All",
            showLess: "Show Less",
            noData: "No data found",
            error: "Error",
            success: "Success",
            status: "Status",
            date: "Date",
            amount: "Amount",
            quantity: "Quantity",
            price: "Price",
            name: "Name",
            description: "Description",
            category: "Category",
            all: "All",
            actions: "Actions",
            details: "Details",
            message: "Message",
            notes: "Notes",
            signOut: "Sign out",
            myAccount: "My Account",
            settings: "Settings",
            welcome: "Welcome",
            perKg: "/kg",
        },
        // Layout / Navigation
        layout: {
            buyerDashboard: "Buyer Dashboard",
            sellerDashboard: "Seller Dashboard",
            shippingDashboard: "Shipping Provider Dashboard",
            adminDashboard: "Admin Dashboard",
            browseItems: "Browse Items",
            myBidRequests: "My Bid Requests",
            sellerBids: "Seller Bids",
            cardamomPrices: "Cardamom Prices",
            dashboard: "Dashboard",
            buyerOrders: "Buyer Orders",
            myBids: "My Bids",
            availableOrders: "Available Orders",
            myShippingBids: "My Shipping Bids",
            overview: "Overview",
            manageItems: "Manage Items",
            manageOrders: "Manage Orders",
            users: "Users",
            rfqs: "RFQs",
            marketPrices: "Market Prices",
        },
        // Status labels
        status: {
            pending: "Pending",
            accepted: "Accepted",
            rejected: "Rejected",
            completed: "Completed",
            cancelled: "Cancelled",
            active: "Active",
            inactive: "Inactive",
            open: "Open",
            closed: "Closed",
            draft: "Draft",
            awarded: "Awarded",
            sold: "Sold",
        },
        // Buyer Dashboard
        buyer: {
            pageTitle: "Buyer Dashboard",
            browseItems: "Browse Items",
            myOrders: "My Bid Requests",
            sellerBids: "Seller Bids",
            stats: {
                totalOrders: "Total Orders",
                pendingBids: "Pending Bids",
                acceptedBids: "Accepted Bids",
                totalSpent: "Total Spent",
                activeOrders: "Active Orders",
                completedOrders: "Completed",
                allTimeOrdersPlaced: "All time orders placed",
                ordersAcceptedBySellers: "Orders accepted by sellers",
                awaitingDelivery: "Awaiting delivery",
                bidsAwaitingResponse: "Bids awaiting your response",
            },
            createOrder: "Create Bid Request",
            newOrder: "New Bid Request",
            placeOrder: "Place Order",
            selectProduct: "Select Product",
            quantity: "Quantity (kg)",
            deliveryAddress: "Delivery Address",
            specialInstructions: "Special Instructions",
            bidDeadline: "Bid Deadline",
            orderPlaced: "Order placed successfully!",
            orderFailed: "Failed to place order",
            noItems: "No items available",
            noBids: "No bids yet",
            noOrders: "No orders yet",
            acceptBid: "Accept Bid",
            rejectBid: "Reject Bid",
            viewBids: "View Bids",
            orderDetails: "Order Details",
            bidDetails: "Bid Details",
            estimatedDelivery: "Estimated Delivery",
            bidAmount: "Bid Amount",
            sellerName: "Seller",
            timeRemaining: "Time Remaining",
            expired: "Expired",
            lowestBid: "Lowest Bid",
            highestBid: "Highest Bid",
            acceptedBid: "Accepted Bid",
            shippingBids: "Shipping Bids",
            deliveryBid: "Delivery Bid",
            acceptShipping: "Accept Shipping",
            totalBids: "Total Bids",
            analytics: "Analytics",
            recentOrders: "Recent Orders",
            searchPlaceholder: "Search products...",
            filterByCategory: "Filter by category",
            sortBy: "Sort by",
            congratulations: "Congratulations!",
            bidAccepted: "Bid accepted successfully",
            placeBidRequestTitle: "Place Bid Request",
            placeBidRequestDesc: "Create a bid request for sellers to submit their offers.",
            productNameRequired: "Product Name *",
            enterProductOrCatalog: "Enter product name or select from catalog",
            catalog: "Catalog",
            hsnCodeLabel: "HSN Code",
            hsnPlaceholder: "e.g., 0909",
            sizeUnitLabel: "Size / Unit *",
            sizePlaceholder: "Select size/unit",
            specificationVariety: "Specification / Variety",
            specificationPlaceholder: "e.g., Singapore Quality, Bold",
            qualityGrade: "Quality Grade *",
            qualityPlaceholder: "Select quality",
            quantityRequired: "Quantity *",
            quantityPlaceholder: "Enter quantity",
            expectedDeliveryDateRequired: "Expected Delivery Date *",
            biddingTimeline: "Bidding Timeline",
            biddingTimelineDesc: "Set how long sellers can bid on your order.",
            sellerBidRunningTimeRequired: "Seller Bid Running Time *",
            selectDuration: "Select duration...",
            sixHours: "6 Hours",
            twelveHours: "12 Hours",
            twentyFourHours: "24 Hours",
            fortyEightHours: "48 Hours",
            seventyTwoHours: "72 Hours",
            hourUnit: "hours",
            sellerBidTimelineHint: "Sellers will have this many hours to place bids.",
            shippingBidAutoHint: "Shipping providers get 24 hours after seller selection.",
            destinationCountryRequired: "Destination Country *",
            selectCountry: "Select country",
            incotermsRequired: "Incoterms *",
            selectIncoterms: "Select Incoterms",
            pincodeRequired: "Pincode *",
            pincodePlaceholder: "6-digit pincode",
            cityRequired: "City *",
            cityPlaceholder: "Enter city",
            stateRequired: "State *",
            selectState: "Select state",
            stateProvince: "State/Province",
            stateProvincePlaceholder: "Enter state/province",
            shippingAddressRequired: "Complete Shipping Address *",
            shippingAddressPlaceholder: "Enter street address, landmark, etc.",
            additionalNotesOptional: "Additional Notes (Optional)",
            additionalNotesPlaceholder: "Any special requirements or notes for sellers...",
            bidRequestSummary: "Bid Request Summary",
            destination: "Destination",
            expectedBy: "Expected By",
            sellerBidTime: "Seller Bid Time",
            shippingBidTime: "Shipping Bid Time",
            placingRequest: "Placing Request...",
            mustLoginBidRequest: "You must be logged in to place a bid request.",
            fillRequiredBidFields: "Please fill in all required bid request fields.",
            fillPincodeState: "Please fill in pincode and state for India.",
            invalidPincode: "Please enter a valid 6-digit pincode.",
            selectIncotermsValidation: "Please select Incoterms for international shipments.",
            invalidSellerBidTime: "Please enter a valid seller bid running time (minimum 1 day).",
            invalidShippingBidTime: "Please enter a valid shipping bid running time (minimum 1 day).",
            bidRequestPlacedTitle: "Bid Request Placed",
            bidRequestPlacedDescription: "Your bid request has been placed successfully.",
            bidRequestFailed: "Failed to place bid request. Please try again.",
            // Live Bids section
            liveBidsSearchPlaceholder: "Search by product name, order ID, or seller ID...",
            sortEndingTime: "Ending Time",
            noLiveBids: "No live bids available",
            noBidsMatchSearch: "No bids match your search",
            sellerBidLabel: "Seller Bid",
            exclusiveGST: "exclusive GST",
            shippingCostLabel: "Shipping Cost",
            noBidYet: "No bid yet",
            shippingBidsCount: "shipping bids",
            totalCostLabel: "Total Cost",
            bestValueLabel: "Best Value",
            internationalShipping: "International Shipping",
            incotermsLabel: "Incoterms",
            domesticShipping: "Domestic Shipping",
            indiaDomestic: "India (Domestic)",
            // Analytics section
            orderStatusDistribution: "Order Status Distribution",
            ordersOverview: "Overview of your orders",
            noOrderData: "No order data available",
            procurementMetrics: "Procurement Metrics",
            purchasingActivity: "Your purchasing activity",
            totalBidsReceived: "Total Bids Received",
            activeRequests: "Active Requests",
            costSavingsSummary: "Cost Savings Summary",
            procurementSavings: "Your procurement savings",
            potentialSavings: "Potential Savings",
            savingsRate: "Savings Rate",
            monthlySpendingTrends: "Monthly Spending Trends",
            spendingOverTime: "Your procurement spending over time",
            bidActivityTimeline: "Bid Activity Timeline",
            bidsPerMonth: "Number of bids received per month",
        },
        // Seller Dashboard
        seller: {
            pageTitle: "Seller Dashboard",
            stats: {
                totalOrders: "Total Orders",
                pendingBids: "Pending Bids",
                acceptedBids: "Accepted Bids",
                rejectedBids: "Rejected Bids",
                totalRevenue: "Total Revenue",
                potentialRevenue: "Potential Revenue",
            },
            buyerOrders: "Buyer Orders",
            myBids: "My Bids",
            submitBid: "Submit Bid",
            updateBid: "Update Bid",
            bidAmount: "Bid Amount (₹/kg)",
            estimatedDelivery: "Estimated Delivery Date",
            pickupAddress: "Pickup Address",
            message: "Message to Buyer",
            noBids: "No bids submitted yet",
            noOrders: "No buyer orders available",
            bidSubmitted: "Bid submitted successfully",
            bidUpdated: "Bid updated successfully",
            analytics: "Analytics",
            revenueOverview: "Revenue Overview",
            bidStatus: "Bid Status",
            searchOrders: "Search orders...",
            searchBids: "Search bids...",
            filterStatus: "Filter by status",
            yourBid: "Your bid",
            competingBids: "other bids",
            lowestBid: "Lowest bid so far",
            youAreLowest: "You are the lowest bidder!",
            // Stats subtitles
            stats_ordersAvailable: "Orders available for bidding",
            stats_activeBidsPlaced: "Active bids placed",
            stats_awaitingResponse: "Awaiting response",
            stats_confirmedOrders: "Confirmed orders",
            stats_fromAcceptedBids: "From accepted bids",
            // Badges & labels
            newBadge: "new",
            liveBadge: "live",
            available: "available",
            refreshing: "Refreshing...",
            clearFilters: "Clear Filters",
            searchOrdersPlaceholder: "Search by product name, order ID, or HSN code...",
            allCategories: "All Categories",
            sortDateCreated: "Date Created",
            sortTotalPrice: "Total Price",
            sortProductName: "Product Name",
            sortBidAmount: "Bid Amount",
            sortDeliveryDate: "Delivery Date",
            noOrdersFiltered: "No orders found matching your filters.",
            newRequests: "NEW REQUESTS",
            product: "Product",
            hsnCode: "HSN Code",
            quality: "Quality",
            size: "Size",
            units: "units",
            expectedDelivery: "Expected Delivery",
            pincode: "Pincode",
            bidRunningTill: "Bid Running Till",
            searchBidsPlaceholder: "Search by product name, order ID, or message...",
            allStatus: "All Status",
            deliveryDate: "Delivery Date",
            noBidsYet: "You haven't placed any bids yet.",
            noBidsFiltered: "No bids found matching your filters.",
            orderNumber: "Order #",
            placedOn: "Placed on",
            orderBudget: "Order Budget",
            qualityCondition: "Quality/Condition",
            analyticsOverview: "Analytics Overview",
            bidStatusDistribution: "Bid Status Distribution",
            bidOutcomesOverview: "Overview of your bid outcomes",
            noBidData: "No bid data available",
            performanceMetrics: "Performance Metrics",
            overallSuccessRate: "Your overall success rate",
            bidSuccessRate: "Bid Success Rate",
            totalBids: "Total Bids",
            totalValue: "Total Value",
            revenueSummary: "Revenue Summary",
            earningsOverview: "Your earnings overview",
            totalPotential: "Total Potential",
            confirmedRevenue: "Confirmed Revenue",
            avgBidValue: "Avg. Bid Value",
            monthlyRevenueTrends: "Monthly Revenue Trends",
            earningsOverTime: "Your earnings from accepted bids over time",
            acceptedRevenue: "Accepted Revenue",
            totalBidValueLabel: "Total Bid Value",
            last7DaysActivity: "Last 7 Days Activity",
            recentBiddingActivity: "Your recent bidding activity",
            onlyBidder: "You're the only bidder!",
            leading: "Leading",
            onlyBidderMessage: "Your bid is currently the only offer for this order. You have a high chance of winning!",
            rank: "Rank",
            bestPriceLabel: "Best Price",
            highestPriceLabel: "Highest Price",
            youHaveLowestBid: "You have the lowest bid",
            veryCompetitive: "Very Competitive",
            competitive: "Competitive",
            highPrice: "High Price",
            loadMore: "Load More",
            more: "more",
            enquiryNumber: "Enquiry Number",
            loadingDashboard: "Loading dashboard...",
            bidCount: "bids",
            enterBidAmount: "Enter your bid amount",
            orderBudgetLabel: "Order budget:",
            personalizedMessage: "Add a personalized message to increase your chances...",
            otherSeller: "other seller",
            otherSellers: "other sellers",
            reduceByApprox: "Reduce by approx.",
            toMatchBest: "to match best",
            onlyWord: "Only",
            aboveLowest: "above lowest",
            higherThanLowest: "higher than lowest",
            bidsLabel: "Bids:",
            valueLabel: "Value:",
            bidAcceptedStatus: "Bid Accepted",
            bidRejectedStatus: "Bid Rejected",
            loginToPlaceBid: "Please log in to place a bid.",
            selectOrderToBid: "Please select an order to bid on.",
            noBidSelectedForEdit: "No bid selected for editing.",
            fillBidAmountDelivery: "Please fill in bid amount and delivery date.",
            enterValidBidAmount: "Please enter a valid bid amount.",
            bidSubmittedDescription: "Your bid has been submitted successfully.",
            bidUpdatedDescription: "Your bid has been updated successfully.",
            failedCreateBid: "Failed to create bid. Please try again.",
            failedUpdateBid: "Failed to update bid. Please try again.",
        },
        // Admin Dashboard
        admin: {
            pageTitle: "Admin Dashboard",
            stats: {
                totalItems: "Total Items",
                totalOrders: "Total Orders",
                totalBids: "Total Bids",
                totalUsers: "Total Users",
                activeItems: "Active Items",
                pendingOrders: "Pending Orders",
                totalRevenue: "Total Revenue",
            },
            addItem: "Add Item",
            editItem: "Edit Item",
            deleteItem: "Delete Item",
            addSeller: "Add Seller",
            manageItems: "Manage Items",
            manageOrders: "Manage Orders",
            manageUsers: "Users",
            confirmDelete: "Are you sure you want to delete this item?",
            itemName: "Item Name",
            itemDescription: "Description",
            itemPrice: "Price",
            itemCategory: "Category",
            itemQuantity: "Quantity",
            itemCondition: "Condition",
            specifications: "Specifications",
            addSpec: "Add Specification",
            sellerEmail: "Seller Email",
            sellerName: "Seller Name",
            sellerPassword: "Password",
            createSellerAccount: "Create Seller Account",
        },
        // Shipping Provider Dashboard
        shipping: {
            pageTitle: "Shipping Provider Dashboard",
            stats: {
                totalOrders: "Available Orders",
                pendingBids: "Pending Bids",
                acceptedBids: "Accepted Bids",
                rejectedBids: "Rejected Bids",
                potentialRevenue: "Potential Revenue",
                totalBidValue: "Total Bid Value",
            },
            availableOrders: "Available Orders",
            myBids: "My Shipping Bids",
            submitBid: "Submit Bid",
            updateBid: "Update Bid",
            bidAmount: "Bid Amount (₹)",
            estimatedDelivery: "Estimated Delivery Date",
            message: "Message",
            noBids: "No shipping bids submitted yet",
            noOrders: "No orders available for shipping",
            bidSubmitted: "Shipping bid submitted",
            bidUpdated: "Shipping bid updated",
            pickupAddress: "Pickup Address",
            deliveryAddress: "Delivery Address",
            distance: "Distance",
            analytics: "Analytics",
        },
        // Cardamom Prices
        cardamom: {
            pageTitle: "Cardamom Market Prices",
            liveData: "Live Market Data",
            lastUpdated: "Last Updated",
            grade: "Grade",
            minPrice: "Min Price",
            maxPrice: "Max Price",
            modalPrice: "Modal Price",
            market: "Market",
            commodity: "Commodity",
            variety: "Variety",
            noData: "No price data available",
            refreshData: "Refresh Data",
            lastUpdatedPrefix: "Last updated:",
            priceHistoryTitle: "Price History (Last 10 Days)",
            priceHistoryDesc: "Average cardamom modal price trend",
            modalPriceLabel: "Modal Price (₹/kg)",
            visitMarketPrices: "Visit Market Prices page to load data",
            todaysPrices: "Today's Prices",
            latestAvailablePrices: "Latest available cardamom prices",
            avgPrice: "Avg",
            noPricesToday: "No prices for today",
            refreshMarketData: "Refresh market data",
            viewAll: "View all",
        },
        // RFQ Management
        rfq: {
            pageTitle: "RFQ Management",
            createRFQ: "Create New RFQ",
            myRFQs: "My RFQs",
            totalRFQs: "Total RFQs",
            openRFQs: "Open RFQs",
            awarded: "Awarded",
            totalQuotes: "Total Quotes",
            rfqTitle: "RFQ Title",
            rfqDescription: "Description",
            deadline: "Deadline",
            viewDetails: "View Details",
            noRFQs: "No RFQs found",
            manageQuotes: "Manage your Request for Quotes",
        },
        // Market Prices
        market: {
            pageTitle: "Market Prices",
            liveUpdates: "Live Updates",
            historicalData: "Historical Data",
        },
    },

    // ─── Hindi ─────────────────────────────────────────────────────────────────
    hi: {
        common: {
            loading: "लोड हो रहा है...",
            save: "सहेजें",
            cancel: "रद्द करें",
            delete: "हटाएं",
            edit: "संपादित करें",
            create: "बनाएं",
            submit: "जमा करें",
            close: "बंद करें",
            confirm: "पुष्टि करें",
            search: "खोजें",
            filter: "फ़िल्टर",
            sort: "क्रमबद्ध करें",
            refresh: "ताज़ा करें",
            viewAll: "सभी देखें",
            showLess: "कम दिखाएं",
            noData: "कोई डेटा नहीं मिला",
            error: "त्रुटि",
            success: "सफलता",
            status: "स्थिति",
            date: "तारीख",
            amount: "राशि",
            quantity: "मात्रा",
            price: "मूल्य",
            name: "नाम",
            description: "विवरण",
            category: "श्रेणी",
            all: "सभी",
            actions: "क्रियाएं",
            details: "विवरण",
            message: "संदेश",
            notes: "नोट्स",
            signOut: "साइन आउट",
            myAccount: "मेरा खाता",
            settings: "सेटिंग्स",
            welcome: "स्वागत है",
            perKg: "/किग्रा",
        },
        layout: {
            buyerDashboard: "खरीदार डैशबोर्ड",
            sellerDashboard: "विक्रेता डैशबोर्ड",
            shippingDashboard: "शिपिंग प्रदाता डैशबोर्ड",
            adminDashboard: "व्यवस्थापक डैशबोर्ड",
            browseItems: "उत्पाद देखें",
            myBidRequests: "मेरी बोली अनुरोध",
            sellerBids: "विक्रेता बोलियां",
            cardamomPrices: "इलायची भाव",
            dashboard: "डैशबोर्ड",
            buyerOrders: "खरीदार ऑर्डर",
            myBids: "मेरी बोलियां",
            availableOrders: "उपलब्ध ऑर्डर",
            myShippingBids: "मेरी शिपिंग बोलियां",
            overview: "अवलोकन",
            manageItems: "उत्पाद प्रबंधन",
            manageOrders: "ऑर्डर प्रबंधन",
            users: "उपयोगकर्ता",
            rfqs: "आरएफक्यू",
            marketPrices: "बाज़ार भाव",
        },
        status: {
            pending: "लंबित",
            accepted: "स्वीकृत",
            rejected: "अस्वीकृत",
            completed: "पूर्ण",
            cancelled: "रद्द",
            active: "सक्रिय",
            inactive: "निष्क्रिय",
            open: "खुला",
            closed: "बंद",
            draft: "मसौदा",
            awarded: "पुरस्कृत",
            sold: "बेचा गया",
        },
        buyer: {
            pageTitle: "खरीदार डैशबोर्ड",
            browseItems: "उत्पाद देखें",
            myOrders: "मेरी बोली अनुरोध",
            sellerBids: "विक्रेता बोलियां",
            stats: {
                totalOrders: "कुल ऑर्डर",
                pendingBids: "लंबित बोलियां",
                acceptedBids: "स्वीकृत बोलियां",
                totalSpent: "कुल खर्च",
                activeOrders: "सक्रिय ऑर्डर",
                completedOrders: "पूर्ण",
                allTimeOrdersPlaced: "सभी समय के ऑर्डर",
                ordersAcceptedBySellers: "विक्रेताओं द्वारा स्वीकृत ऑर्डर",
                awaitingDelivery: "डिलीवरी की प्रतीक्षा में",
                bidsAwaitingResponse: "आपकी प्रतिक्रिया की प्रतीक्षा में बोलियां",
            },
            createOrder: "बोली अनुरोध बनाएं",
            newOrder: "नया बोली अनुरोध",
            placeOrder: "ऑर्डर दें",
            selectProduct: "उत्पाद चुनें",
            quantity: "मात्रा (किग्रा)",
            deliveryAddress: "डिलीवरी पता",
            specialInstructions: "विशेष निर्देश",
            bidDeadline: "बोली की समय सीमा",
            orderPlaced: "ऑर्डर सफलतापूर्वक दिया गया!",
            orderFailed: "ऑर्डर देने में विफल",
            noItems: "कोई उत्पाद उपलब्ध नहीं",
            noBids: "अभी तक कोई बोली नहीं",
            noOrders: "अभी तक कोई ऑर्डर नहीं",
            acceptBid: "बोली स्वीकार करें",
            rejectBid: "बोली अस्वीकार करें",
            viewBids: "बोलियां देखें",
            orderDetails: "ऑर्डर विवरण",
            bidDetails: "बोली विवरण",
            estimatedDelivery: "अनुमानित डिलीवरी",
            bidAmount: "बोली राशि",
            sellerName: "विक्रेता",
            timeRemaining: "शेष समय",
            expired: "समाप्त",
            lowestBid: "सबसे कम बोली",
            highestBid: "सबसे अधिक बोली",
            acceptedBid: "स्वीकृत बोली",
            shippingBids: "शिपिंग बोलियां",
            deliveryBid: "डिलीवरी बोली",
            acceptShipping: "शिपिंग स्वीकार करें",
            totalBids: "कुल बोलियां",
            analytics: "विश्लेषण",
            recentOrders: "हाल के ऑर्डर",
            searchPlaceholder: "उत्पाद खोजें...",
            filterByCategory: "श्रेणी के अनुसार फ़िल्टर",
            sortBy: "क्रमबद्ध करें",
            congratulations: "बधाई!",
            bidAccepted: "बोली सफलतापूर्वक स्वीकार की गई",
            placeBidRequestTitle: "बोली अनुरोध रखें",
            placeBidRequestDesc: "विक्रेताओं से ऑफर प्राप्त करने के लिए बोली अनुरोध बनाएं।",
            productNameRequired: "उत्पाद नाम *",
            enterProductOrCatalog: "उत्पाद नाम लिखें या कैटलॉग से चुनें",
            catalog: "कैटलॉग",
            hsnCodeLabel: "एचएसएन कोड",
            hsnPlaceholder: "जैसे 0909",
            sizeUnitLabel: "आकार / इकाई *",
            sizePlaceholder: "आकार/इकाई चुनें",
            specificationVariety: "विशेषता / वैरायटी",
            specificationPlaceholder: "जैसे सिंगापुर क्वालिटी, बोल्ड",
            qualityGrade: "गुणवत्ता ग्रेड *",
            qualityPlaceholder: "गुणवत्ता चुनें",
            quantityRequired: "मात्रा *",
            quantityPlaceholder: "मात्रा दर्ज करें",
            expectedDeliveryDateRequired: "अपेक्षित डिलीवरी तिथि *",
            biddingTimeline: "बोली समयरेखा",
            biddingTimelineDesc: "विक्रेताओं के लिए बोली अवधि तय करें।",
            sellerBidRunningTimeRequired: "विक्रेता बोली अवधि *",
            selectDuration: "अवधि चुनें...",
            sixHours: "6 घंटे",
            twelveHours: "12 घंटे",
            twentyFourHours: "24 घंटे",
            fortyEightHours: "48 घंटे",
            seventyTwoHours: "72 घंटे",
            hourUnit: "घंटे",
            sellerBidTimelineHint: "विक्रेताओं को बोली लगाने के लिए इतने घंटे मिलेंगे।",
            shippingBidAutoHint: "विक्रेता चयन के बाद शिपिंग को 24 घंटे मिलेंगे।",
            destinationCountryRequired: "गंतव्य देश *",
            selectCountry: "देश चुनें",
            incotermsRequired: "इन्कोटर्म्स *",
            selectIncoterms: "इन्कोटर्म्स चुनें",
            pincodeRequired: "पिनकोड *",
            pincodePlaceholder: "6 अंकों का पिनकोड",
            cityRequired: "शहर *",
            cityPlaceholder: "शहर दर्ज करें",
            stateRequired: "राज्य *",
            selectState: "राज्य चुनें",
            stateProvince: "राज्य/प्रांत",
            stateProvincePlaceholder: "राज्य/प्रांत दर्ज करें",
            shippingAddressRequired: "पूरा शिपिंग पता *",
            shippingAddressPlaceholder: "सड़क पता, लैंडमार्क आदि दर्ज करें",
            additionalNotesOptional: "अतिरिक्त नोट्स (वैकल्पिक)",
            additionalNotesPlaceholder: "विक्रेताओं के लिए विशेष आवश्यकताएं या नोट्स...",
            bidRequestSummary: "बोली अनुरोध सारांश",
            destination: "गंतव्य",
            expectedBy: "अपेक्षित तिथि",
            sellerBidTime: "विक्रेता बोली समय",
            shippingBidTime: "शिपिंग बोली समय",
            placingRequest: "अनुरोध भेजा जा रहा है...",
            mustLoginBidRequest: "बोली अनुरोध रखने के लिए लॉगिन करें।",
            fillRequiredBidFields: "कृपया सभी आवश्यक बोली फ़ील्ड भरें।",
            fillPincodeState: "भारत के लिए पिनकोड और राज्य भरें।",
            invalidPincode: "मान्य 6 अंकों का पिनकोड दर्ज करें।",
            selectIncotermsValidation: "अंतरराष्ट्रीय शिपमेंट के लिए इन्कोटर्म्स चुनें।",
            invalidSellerBidTime: "मान्य विक्रेता बोली अवधि दर्ज करें (कम से कम 1 दिन)।",
            invalidShippingBidTime: "मान्य शिपिंग बोली अवधि दर्ज करें (कम से कम 1 दिन)।",
            bidRequestPlacedTitle: "बोली अनुरोध रखा गया",
            bidRequestPlacedDescription: "आपका बोली अनुरोध सफलतापूर्वक रखा गया है।",
            bidRequestFailed: "बोली अनुरोध रखने में विफल। फिर कोशिश करें।",
            liveBidsSearchPlaceholder: "उत्पाद नाम, ऑर्डर आईडी, या विक्रेता आईडी से खोजें...",
            sortEndingTime: "समाप्ति समय",
            noLiveBids: "कोई लाइव बोलियां उपलब्ध नहीं",
            noBidsMatchSearch: "कोई बोली आपकी खोज से मेल नहीं खाती",
            sellerBidLabel: "विक्रेता बोली",
            exclusiveGST: "जीएसटी को छोड़कर",
            shippingCostLabel: "शिपिंग लागत",
            noBidYet: "अभी तक कोई बोली नहीं",
            shippingBidsCount: "शिपिंग बोलियां",
            totalCostLabel: "कुल लागत",
            bestValueLabel: "सर्वोत्तम मूल्य",
            internationalShipping: "अंतर्राष्ट्रीय शिपिंग",
            incotermsLabel: "इन्कोटर्म्स",
            domesticShipping: "घरेलू शिपिंग",
            indiaDomestic: "भारत (घरेलू)",
            orderStatusDistribution: "ऑर्डर स्थिति वितरण",
            ordersOverview: "आपके ऑर्डर का अवलोकन",
            noOrderData: "कोई ऑर्डर डेटा उपलब्ध नहीं",
            procurementMetrics: "खरीद मेट्रिक्स",
            purchasingActivity: "आपकी खरीद गतिविधि",
            totalBidsReceived: "कुल प्राप्त बोलियां",
            activeRequests: "सक्रिय अनुरोध",
            costSavingsSummary: "लागत बचत सारांश",
            procurementSavings: "आपकी खरीद बचत",
            potentialSavings: "संभावित बचत",
            savingsRate: "बचत दर",
            monthlySpendingTrends: "मासिक खर्च रुझान",
            spendingOverTime: "समय के साथ आपका खरीद खर्च",
            bidActivityTimeline: "बोली गतिविधि समयरेखा",
            bidsPerMonth: "प्रति माह प्राप्त बोलियों की संख्या",
        },
        seller: {
            pageTitle: "विक्रेता डैशबोर्ड",
            stats: {
                totalOrders: "कुल ऑर्डर",
                pendingBids: "लंबित बोलियां",
                acceptedBids: "स्वीकृत बोलियां",
                rejectedBids: "अस्वीकृत बोलियां",
                totalRevenue: "कुल राजस्व",
                potentialRevenue: "संभावित राजस्व",
            },
            buyerOrders: "खरीदार ऑर्डर",
            myBids: "मेरी बोलियां",
            submitBid: "बोली जमा करें",
            updateBid: "बोली अपडेट करें",
            bidAmount: "बोली राशि (₹/किग्रा)",
            estimatedDelivery: "अनुमानित डिलीवरी तारीख",
            pickupAddress: "पिकअप पता",
            message: "खरीदार को संदेश",
            noBids: "अभी तक कोई बोली जमा नहीं",
            noOrders: "कोई खरीदार ऑर्डर उपलब्ध नहीं",
            bidSubmitted: "बोली सफलतापूर्वक जमा की गई",
            bidUpdated: "बोली सफलतापूर्वक अपडेट की गई",
            analytics: "विश्लेषण",
            revenueOverview: "राजस्व अवलोकन",
            bidStatus: "बोली स्थिति",
            searchOrders: "ऑर्डर खोजें...",
            searchBids: "बोलियां खोजें...",
            filterStatus: "स्थिति के अनुसार फ़िल्टर",
            yourBid: "आपकी बोली",
            competingBids: "अन्य बोलियां",
            lowestBid: "अब तक की सबसे कम बोली",
            youAreLowest: "आप सबसे कम बोली लगाने वाले हैं!",
            stats_ordersAvailable: "बोली के लिए उपलब्ध ऑर्डर",
            stats_activeBidsPlaced: "सक्रिय बोलियां लगाई गई",
            stats_awaitingResponse: "प्रतीक्षारत",
            stats_confirmedOrders: "पुष्टि किए गए ऑर्डर",
            stats_fromAcceptedBids: "स्वीकृत बोलियों से",
            newBadge: "नया",
            liveBadge: "लाइव",
            available: "उपलब्ध",
            refreshing: "ताज़ा हो रहा है...",
            clearFilters: "फ़िल्टर साफ़ करें",
            searchOrdersPlaceholder: "उत्पाद नाम, ऑर्डर आईडी, या एचएसएन कोड से खोजें...",
            allCategories: "सभी श्रेणियां",
            sortDateCreated: "तारीख",
            sortTotalPrice: "कुल मूल्य",
            sortProductName: "उत्पाद नाम",
            sortBidAmount: "बोली राशि",
            sortDeliveryDate: "डिलीवरी तारीख",
            noOrdersFiltered: "आपके फ़िल्टर से कोई ऑर्डर नहीं मिला।",
            newRequests: "नई अनुरोध",
            product: "उत्पाद",
            hsnCode: "एचएसएन कोड",
            quality: "गुणवत्ता",
            size: "आकार",
            units: "इकाइयां",
            expectedDelivery: "अपेक्षित डिलीवरी",
            pincode: "पिनकोड",
            bidRunningTill: "बोली चलती है तक",
            searchBidsPlaceholder: "उत्पाद नाम, ऑर्डर आईडी, या संदेश से खोजें...",
            allStatus: "सभी स्थिति",
            deliveryDate: "डिलीवरी तारीख",
            noBidsYet: "अभी तक कोई बोली नहीं लगाई।",
            noBidsFiltered: "आपके फ़िल्टर से कोई बोली नहीं मिली।",
            orderNumber: "ऑर्डर #",
            placedOn: "दिनांक",
            orderBudget: "ऑर्डर बजट",
            qualityCondition: "गुणवत्ता/स्थिति",
            analyticsOverview: "विश्लेषण अवलोकन",
            bidStatusDistribution: "बोली स्थिति वितरण",
            bidOutcomesOverview: "आपकी बोलियों के परिणाम",
            noBidData: "कोई बोली डेटा उपलब्ध नहीं",
            performanceMetrics: "प्रदर्शन मेट्रिक्स",
            overallSuccessRate: "आपकी समग्र सफलता दर",
            bidSuccessRate: "बोली सफलता दर",
            totalBids: "कुल बोलियां",
            totalValue: "कुल मूल्य",
            revenueSummary: "राजस्व सारांश",
            earningsOverview: "आपकी कमाई का अवलोकन",
            totalPotential: "कुल संभावित",
            confirmedRevenue: "पुष्टि राजस्व",
            avgBidValue: "औसत बोली मूल्य",
            monthlyRevenueTrends: "मासिक राजस्व रुझान",
            earningsOverTime: "स्वीकृत बोलियों से आपकी कमाई",
            acceptedRevenue: "स्वीकृत राजस्व",
            totalBidValueLabel: "कुल बोली मूल्य",
            last7DaysActivity: "पिछले 7 दिनों की गतिविधि",
            recentBiddingActivity: "आपकी हाल की बोली गतिविधि",
            onlyBidder: "आप एकमात्र बोलीदाता हैं!",
            leading: "अग्रणी",
            onlyBidderMessage: "आपकी बोली इस ऑर्डर के लिए एकमात्र ऑफर है। आपके जीतने की बड़ी संभावना है!",
            rank: "रैंक",
            bestPriceLabel: "सर्वोत्तम मूल्य",
            highestPriceLabel: "सबसे अधिक मूल्य",
            youHaveLowestBid: "आपकी सबसे कम बोली है",
            veryCompetitive: "बहुत प्रतिस्पर्धी",
            competitive: "प्रतिस्पर्धी",
            highPrice: "अधिक मूल्य",
            loadMore: "और लोड करें",
            more: "और",
            enquiryNumber: "जांच संख्या",
            loadingDashboard: "डैशबोर्ड लोड हो रहा है...",
            bidCount: "बोलियां",
            enterBidAmount: "अपनी बोली राशि दर्ज करें",
            orderBudgetLabel: "ऑर्डर बजट:",
            personalizedMessage: "अपनी संभावनाओं को बढ़ाने के लिए एक व्यक्तिगत संदेश जोड़ें...",
            otherSeller: "अन्य विक्रेता",
            otherSellers: "अन्य विक्रेता",
            reduceByApprox: "सर्वोत्तम से मेल के लिए लगभग",
            toMatchBest: "कम करें",
            onlyWord: "केवल",
            aboveLowest: "सबसे कम से ऊपर",
            higherThanLowest: "सबसे कम से अधिक",
            bidsLabel: "बोलियां:",
            valueLabel: "मूल्य:",
            bidAcceptedStatus: "बोली स्वीकृत",
            bidRejectedStatus: "बोली अस्वीकृत",
            loginToPlaceBid: "बोली लगाने के लिए लॉगिन करें।",
            selectOrderToBid: "बोली लगाने के लिए ऑर्डर चुनें।",
            noBidSelectedForEdit: "संपादन के लिए कोई बोली चयनित नहीं है।",
            fillBidAmountDelivery: "बोली राशि और डिलीवरी तिथि भरें।",
            enterValidBidAmount: "मान्य बोली राशि दर्ज करें।",
            bidSubmittedDescription: "आपकी बोली सफलतापूर्वक जमा हो गई है।",
            bidUpdatedDescription: "आपकी बोली सफलतापूर्वक अपडेट हो गई है।",
            failedCreateBid: "बोली बनाने में विफल। फिर कोशिश करें।",
            failedUpdateBid: "बोली अपडेट करने में विफल। फिर कोशिश करें।",
        },
        admin: {
            pageTitle: "व्यवस्थापक डैशबोर्ड",
            stats: {
                totalItems: "कुल उत्पाद",
                totalOrders: "कुल ऑर्डर",
                totalBids: "कुल बोलियां",
                totalUsers: "कुल उपयोगकर्ता",
                activeItems: "सक्रिय उत्पाद",
                pendingOrders: "लंबित ऑर्डर",
                totalRevenue: "कुल राजस्व",
            },
            addItem: "उत्पाद जोड़ें",
            editItem: "उत्पाद संपादित करें",
            deleteItem: "उत्पाद हटाएं",
            addSeller: "विक्रेता जोड़ें",
            manageItems: "उत्पाद प्रबंधन",
            manageOrders: "ऑर्डर प्रबंधन",
            manageUsers: "उपयोगकर्ता",
            confirmDelete: "क्या आप इस उत्पाद को हटाना चाहते हैं?",
            itemName: "उत्पाद नाम",
            itemDescription: "विवरण",
            itemPrice: "मूल्य",
            itemCategory: "श्रेणी",
            itemQuantity: "मात्रा",
            itemCondition: "स्थिति",
            specifications: "विनिर्देश",
            addSpec: "विनिर्देश जोड़ें",
            sellerEmail: "विक्रेता ईमेल",
            sellerName: "विक्रेता नाम",
            sellerPassword: "पासवर्ड",
            createSellerAccount: "विक्रेता खाता बनाएं",
        },
        shipping: {
            pageTitle: "शिपिंग प्रदाता डैशबोर्ड",
            stats: {
                totalOrders: "उपलब्ध ऑर्डर",
                pendingBids: "लंबित बोलियां",
                acceptedBids: "स्वीकृत बोलियां",
                rejectedBids: "अस्वीकृत बोलियां",
                potentialRevenue: "संभावित राजस्व",
                totalBidValue: "कुल बोली मूल्य",
            },
            availableOrders: "उपलब्ध ऑर्डर",
            myBids: "मेरी शिपिंग बोलियां",
            submitBid: "बोली जमा करें",
            updateBid: "बोली अपडेट करें",
            bidAmount: "बोली राशि (₹)",
            estimatedDelivery: "अनुमानित डिलीवरी तारीख",
            message: "संदेश",
            noBids: "अभी तक कोई शिपिंग बोली जमा नहीं",
            noOrders: "शिपिंग के लिए कोई ऑर्डर उपलब्ध नहीं",
            bidSubmitted: "शिपिंग बोली जमा की गई",
            bidUpdated: "शिपिंग बोली अपडेट की गई",
            pickupAddress: "पिकअप पता",
            deliveryAddress: "डिलीवरी पता",
            distance: "दूरी",
            analytics: "विश्लेषण",
        },
        cardamom: {
            pageTitle: "इलायची बाज़ार भाव",
            liveData: "लाइव बाज़ार डेटा",
            lastUpdated: "अंतिम अपडेट",
            grade: "ग्रेड",
            minPrice: "न्यूनतम मूल्य",
            maxPrice: "अधिकतम मूल्य",
            modalPrice: "मोडल मूल्य",
            market: "बाज़ार",
            commodity: "वस्तु",
            variety: "किस्म",
            noData: "कोई मूल्य डेटा उपलब्ध नहीं",
            refreshData: "डेटा ताज़ा करें",
            lastUpdatedPrefix: "अंतिम अपडेट:",
            priceHistoryTitle: "मूल्य इतिहास (पिछले 10 दिन)",
            priceHistoryDesc: "औसत इलायची मोडल मूल्य रुझान",
            modalPriceLabel: "मोडल मूल्य (₹/किग्रा)",
            visitMarketPrices: "डेटा लोड करने के लिए बाज़ार भाव पृष्ठ पर जाएं",
            todaysPrices: "आज के भाव",
            latestAvailablePrices: "नवीनतम उपलब्ध इलायची भाव",
            avgPrice: "औसत",
            noPricesToday: "आज के लिए कोई भाव नहीं",
            refreshMarketData: "बाज़ार डेटा ताज़ा करें",
            viewAll: "सभी देखें",
        },
        rfq: {
            pageTitle: "आरएफक्यू प्रबंधन",
            createRFQ: "नया आरएफक्यू बनाएं",
            myRFQs: "मेरे आरएफक्यू",
            totalRFQs: "कुल आरएफक्यू",
            openRFQs: "खुले आरएफक्यू",
            awarded: "पुरस्कृत",
            totalQuotes: "कुल कोटेशन",
            rfqTitle: "आरएफक्यू शीर्षक",
            rfqDescription: "विवरण",
            deadline: "समय सीमा",
            viewDetails: "विवरण देखें",
            noRFQs: "कोई आरएफक्यू नहीं मिला",
            manageQuotes: "अपने कोटेशन अनुरोध प्रबंधित करें",
        },
        market: {
            pageTitle: "बाज़ार भाव",
            liveUpdates: "लाइव अपडेट",
            historicalData: "ऐतिहासिक डेटा",
        },
    },

    // ─── Malayalam ─────────────────────────────────────────────────────────────
    ml: {
        common: {
            loading: "ലോഡ് ചെയ്യുന്നു...",
            save: "സേവ് ചെയ്യുക",
            cancel: "റദ്ദാക്കുക",
            delete: "ഇല്ലാതാക്കുക",
            edit: "എഡിറ്റ് ചെയ്യുക",
            create: "സൃഷ്ടിക്കുക",
            submit: "സമർപ്പിക്കുക",
            close: "അടയ്ക്കുക",
            confirm: "സ്ഥിരീകരിക്കുക",
            search: "തിരയുക",
            filter: "ഫിൽറ്റർ",
            sort: "അടുക്കുക",
            refresh: "പുതുക്കുക",
            viewAll: "എല്ലാം കാണുക",
            showLess: "കുറവ് കാണിക്കുക",
            noData: "ഡാറ്റ കണ്ടെത്തിയില്ല",
            error: "പിശക്",
            success: "വിജയം",
            status: "നില",
            date: "തീയതി",
            amount: "തുക",
            quantity: "അളവ്",
            price: "വില",
            name: "പേര്",
            description: "വിവരണം",
            category: "വിഭാഗം",
            all: "എല്ലാം",
            actions: "പ്രവർത്തനങ്ങൾ",
            details: "വിശദാംശങ്ങൾ",
            message: "സന്ദേശം",
            notes: "കുറിപ്പുകൾ",
            signOut: "സൈൻ ഔട്ട്",
            myAccount: "എന്റെ അക്കൗണ്ട്",
            settings: "ക്രമീകരണങ്ങൾ",
            welcome: "സ്വാഗതം",
            perKg: "/കി.ഗ്രാം",
        },
        layout: {
            buyerDashboard: "വാങ്ങുന്നവരുടെ ഡാഷ്ബോർഡ്",
            sellerDashboard: "വിൽക്കുന്നവരുടെ ഡാഷ്ബോർഡ്",
            shippingDashboard: "ഷിപ്പിംഗ് ദാതാവ് ഡാഷ്ബോർഡ്",
            adminDashboard: "അഡ്മിൻ ഡാഷ്ബോർഡ്",
            browseItems: "ഉൽപ്പന്നങ്ങൾ കാണുക",
            myBidRequests: "എന്റെ ബിഡ് അഭ്യർഥനകൾ",
            sellerBids: "വിൽക്കുന്നവരുടെ ബിഡ്ഡുകൾ",
            cardamomPrices: "ഏലം വില",
            dashboard: "ഡാഷ്ബോർഡ്",
            buyerOrders: "വാങ്ങുന്നവരുടെ ഓർഡറുകൾ",
            myBids: "എന്റെ ബിഡ്ഡുകൾ",
            availableOrders: "ലഭ്യമായ ഓർഡറുകൾ",
            myShippingBids: "എന്റെ ഷിപ്പിംഗ് ബിഡ്ഡുകൾ",
            overview: "അവലോകനം",
            manageItems: "ഉൽപ്പന്ന മാനേജ്‌മെന്റ്",
            manageOrders: "ഓർഡർ മാനേജ്‌മെന്റ്",
            users: "ഉപയോക്താക്കൾ",
            rfqs: "ആർഎഫ്ക്യു",
            marketPrices: "മാർക്കറ്റ് വില",
        },
        status: {
            pending: "പരിഗണനയിൽ",
            accepted: "സ്വീകരിച്ചു",
            rejected: "നിരസിച്ചു",
            completed: "പൂർത്തിയായി",
            cancelled: "റദ്ദാക്കി",
            active: "സജീവം",
            inactive: "നിഷ്ക്രിയം",
            open: "തുറന്നിരിക്കുന്നു",
            closed: "അടഞ്ഞിരിക്കുന്നു",
            draft: "ഡ്രാഫ്റ്റ്",
            awarded: "അവാർഡ് ചെയ്തു",
            sold: "വിറ്റു",
        },
        buyer: {
            pageTitle: "വാങ്ങുന്നവരുടെ ഡാഷ്ബോർഡ്",
            browseItems: "ഉൽപ്പന്നങ്ങൾ കാണുക",
            myOrders: "എന്റെ ബിഡ് അഭ്യർഥനകൾ",
            sellerBids: "വിൽക്കുന്നവരുടെ ബിഡ്ഡുകൾ",
            stats: {
                totalOrders: "മൊത്തം ഓർഡറുകൾ",
                pendingBids: "കാത്തിരിക്കുന്ന ബിഡ്ഡുകൾ",
                acceptedBids: "സ്വീകരിച്ച ബിഡ്ഡുകൾ",
                totalSpent: "മൊത്തം ചെലവ്",
                activeOrders: "സജീവ ഓർഡറുകൾ",
                completedOrders: "പൂർത്തിയായവ",
                allTimeOrdersPlaced: "എക്കാലത്തെ ഓർഡറുകൾ",
                ordersAcceptedBySellers: "വിൽക്കുന്നവർ സ്വീകരിച്ച ഓർഡറുകൾ",
                awaitingDelivery: "ഡെലിവറിക്കായി കാത്തിരിക്കുന്നു",
                bidsAwaitingResponse: "നിങ്ങളുടെ പ്രതികരണത്തിനായി കാത്തിരിക്കുന്ന ബിഡ്ഡുകൾ",
            },
            createOrder: "ബിഡ് അഭ്യർഥന സൃഷ്ടിക്കുക",
            newOrder: "പുതിയ ബിഡ് അഭ്യർഥന",
            placeOrder: "ഓർഡർ നൽകുക",
            selectProduct: "ഉൽപ്പന്നം തിരഞ്ഞെടുക്കുക",
            quantity: "അളവ് (കി.ഗ്രാം)",
            deliveryAddress: "ഡെലിവറി വിലാസം",
            specialInstructions: "പ്രത്യേക നിർദ്ദേശങ്ങൾ",
            bidDeadline: "ബിഡ് സമയ പരിധി",
            orderPlaced: "ഓർഡർ വിജയകരമായി നൽകി!",
            orderFailed: "ഓർഡർ നൽകുന്നതിൽ പരാജയം",
            noItems: "ഉൽപ്പന്നങ്ങൾ ലഭ്യമല്ല",
            noBids: "ഇതുവരെ ബിഡ്ഡുകൾ ഇല്ല",
            noOrders: "ഇതുവരെ ഓർഡറുകൾ ഇല്ല",
            acceptBid: "ബിഡ് സ്വീകരിക്കുക",
            rejectBid: "ബിഡ് നിരസിക്കുക",
            viewBids: "ബിഡ്ഡുകൾ കാണുക",
            orderDetails: "ഓർഡർ വിശദാംശങ്ങൾ",
            bidDetails: "ബിഡ് വിശദാംശങ്ങൾ",
            estimatedDelivery: "ഏകദേശ ഡെലിവറി",
            bidAmount: "ബിഡ് തുക",
            sellerName: "വിൽക്കുന്നയാൾ",
            timeRemaining: "ശേഷിക്കുന്ന സമയം",
            expired: "കാലഹരണപ്പെട്ടു",
            lowestBid: "ഏറ്റവും കുറഞ്ഞ ബിഡ്",
            highestBid: "ഏറ്റവും ഉയർന്ന ബിഡ്",
            acceptedBid: "സ്വീകരിച്ച ബിഡ്",
            shippingBids: "ഷിപ്പിംഗ് ബിഡ്ഡുകൾ",
            deliveryBid: "ഡെലിവറി ബിഡ്",
            acceptShipping: "ഷിപ്പിംഗ് സ്വീകരിക്കുക",
            totalBids: "മൊത്തം ബിഡ്ഡുകൾ",
            analytics: "വിശകലനം",
            recentOrders: "സമീപകാല ഓർഡറുകൾ",
            searchPlaceholder: "ഉൽപ്പന്നങ്ങൾ തിരയുക...",
            filterByCategory: "വിഭാഗം അനുസരിച്ച് ഫിൽറ്റർ ചെയ്യുക",
            sortBy: "അടുക്കുക",
            congratulations: "അഭിനന്ദനങ്ങൾ!",
            bidAccepted: "ബിഡ് വിജയകരമായി സ്വീകരിച്ചു",
            placeBidRequestTitle: "ബിഡ് അഭ്യർഥന സമർപ്പിക്കുക",
            placeBidRequestDesc: "വിൽപ്പനക്കാരിൽ നിന്ന് ഓഫറുകൾ ലഭിക്കാൻ ബിഡ് അഭ്യർഥന സൃഷ്ടിക്കുക.",
            productNameRequired: "ഉൽപ്പന്നത്തിന്റെ പേര് *",
            enterProductOrCatalog: "ഉൽപ്പന്നത്തിന്റെ പേര് നൽകുക അല്ലെങ്കിൽ കാറ്റലോഗിൽ നിന്ന് തിരഞ്ഞെടുക്കുക",
            catalog: "കാറ്റലോഗ്",
            hsnCodeLabel: "HSN കോഡ്",
            hsnPlaceholder: "ഉദാ., 0909",
            sizeUnitLabel: "വലുപ്പം / യൂണിറ്റ് *",
            sizePlaceholder: "വലുപ്പം/യൂണിറ്റ് തിരഞ്ഞെടുക്കുക",
            specificationVariety: "സ്പെസിഫിക്കേഷൻ / ഇനം",
            specificationPlaceholder: "ഉദാ., Singapore Quality, Bold",
            qualityGrade: "ഗുണനിലവാര ഗ്രേഡ് *",
            qualityPlaceholder: "ഗുണനിലവാരം തിരഞ്ഞെടുക്കുക",
            quantityRequired: "അളവ് *",
            quantityPlaceholder: "അളവ് നൽകുക",
            expectedDeliveryDateRequired: "പ്രതീക്ഷിക്കുന്ന ഡെലിവറി തീയതി *",
            biddingTimeline: "ബിഡ്ഡിംഗ് ടൈംലൈൻ",
            biddingTimelineDesc: "വിൽപ്പനക്കാരുടെ ബിഡ്ഡിംഗ് കാലാവധി നിശ്ചയിക്കുക.",
            sellerBidRunningTimeRequired: "വിൽപ്പനക്കാരുടെ ബിഡ് സമയം *",
            selectDuration: "ദൈർഘ്യം തിരഞ്ഞെടുക്കുക...",
            sixHours: "6 മണിക്കൂർ",
            twelveHours: "12 മണിക്കൂർ",
            twentyFourHours: "24 മണിക്കൂർ",
            fortyEightHours: "48 മണിക്കൂർ",
            seventyTwoHours: "72 മണിക്കൂർ",
            hourUnit: "മണിക്കൂർ",
            sellerBidTimelineHint: "വിൽപ്പനക്കാർക്ക് ബിഡ് ചെയ്യാൻ ഇത്ര മണിക്കൂർ ലഭിക്കും.",
            shippingBidAutoHint: "വിൽപ്പനക്കാരനെ തെരഞ്ഞെടുത്തതിന് ശേഷം ഷിപ്പിംഗിന് 24 മണിക്കൂർ ലഭിക്കും.",
            destinationCountryRequired: "ലക്ഷ്യരാജ്യം *",
            selectCountry: "രാജ്യം തിരഞ്ഞെടുക്കുക",
            incotermsRequired: "Incoterms *",
            selectIncoterms: "Incoterms തിരഞ്ഞെടുക്കുക",
            pincodeRequired: "പിൻകോഡ് *",
            pincodePlaceholder: "6 അക്ക പിൻകോഡ്",
            cityRequired: "നഗരം *",
            cityPlaceholder: "നഗരം നൽകുക",
            stateRequired: "സംസ്ഥാനം *",
            selectState: "സംസ്ഥാനം തിരഞ്ഞെടുക്കുക",
            stateProvince: "സംസ്ഥാനം/പ്രവിശ്യ",
            stateProvincePlaceholder: "സംസ്ഥാനം/പ്രവിശ്യ നൽകുക",
            shippingAddressRequired: "പൂർണ്ണ ഷിപ്പിംഗ് വിലാസം *",
            shippingAddressPlaceholder: "വീഥി വിലാസം, ലാൻഡ്മാർക്ക് തുടങ്ങിയവ നൽകുക",
            additionalNotesOptional: "കൂടുതൽ കുറിപ്പുകൾ (ഐച്ഛികം)",
            additionalNotesPlaceholder: "വിൽപ്പനക്കാരർക്കുള്ള പ്രത്യേക ആവശ്യങ്ങൾ അല്ലെങ്കിൽ കുറിപ്പുകൾ...",
            bidRequestSummary: "ബിഡ് അഭ്യർഥന സംഗ്രഹം",
            destination: "ലക്ഷ്യം",
            expectedBy: "പ്രതീക്ഷിക്കുന്ന തീയതി",
            sellerBidTime: "വിൽപ്പനക്കാരന്റെ ബിഡ് സമയം",
            shippingBidTime: "ഷിപ്പിംഗ് ബിഡ് സമയം",
            placingRequest: "അഭ്യർഥന സമർപ്പിക്കുന്നു...",
            mustLoginBidRequest: "ബിഡ് അഭ്യർഥനയ്ക്ക് ലോഗിൻ ചെയ്യുക.",
            fillRequiredBidFields: "ആവശ്യമായ എല്ലാ ബിഡ് ഫീൽഡുകളും പൂരിപ്പിക്കുക.",
            fillPincodeState: "ഇന്ത്യയ്ക്കായി പിൻകോഡും സംസ്ഥാനവും പൂരിപ്പിക്കുക.",
            invalidPincode: "ശരിയായ 6 അക്ക പിൻകോഡ് നൽകുക.",
            selectIncotermsValidation: "അന്തർദേശീയ ഷിപ്പ്മെന്റുകൾക്കായി Incoterms തിരഞ്ഞെടുക്കുക.",
            invalidSellerBidTime: "ശരിയായ വിൽപ്പനക്കാരൻ ബിഡ് സമയം നൽകുക (കുറഞ്ഞത് 1 ദിവസം).",
            invalidShippingBidTime: "ശരിയായ ഷിപ്പിംഗ് ബിഡ് സമയം നൽകുക (കുറഞ്ഞത് 1 ദിവസം).",
            bidRequestPlacedTitle: "ബിഡ് അഭ്യർഥന സമർപ്പിച്ചു",
            bidRequestPlacedDescription: "നിങ്ങളുടെ ബിഡ് അഭ്യർഥന വിജയകരമായി സമർപ്പിച്ചു.",
            bidRequestFailed: "ബിഡ് അഭ്യർഥന സമർപ്പിക്കാൻ സാധിച്ചില്ല. വീണ്ടും ശ്രമിക്കുക.",
            liveBidsSearchPlaceholder: "ഉൽപ്പന്ന പേര്, ഓർഡർ ഐഡി, അല്ലെങ്കിൽ വിൽക്കുന്നയാൾ ഐഡി ഉപയോഗിച്ച് തിരയുക...",
            sortEndingTime: "അവസാന സമയം",
            noLiveBids: "ലൈവ് ബിഡ്ഡുകൾ ഇല്ല",
            noBidsMatchSearch: "നിങ്ങളുടെ തിരയലിന് അനുയോജ്യമായ ബിഡ്ഡുകൾ ഇല്ല",
            sellerBidLabel: "വിൽക്കുന്നയാളുടെ ബിഡ്",
            exclusiveGST: "ജിഎസ്ടി ഒഴികെ",
            shippingCostLabel: "ഷിപ്പിംഗ് ചെലവ്",
            noBidYet: "ഇതുവരെ ബിഡ് ഇല്ല",
            shippingBidsCount: "ഷിപ്പിംഗ് ബിഡ്ഡുകൾ",
            totalCostLabel: "മൊത്തം ചെലവ്",
            bestValueLabel: "ഏറ്റവും മികച്ച മൂല്യം",
            internationalShipping: "അന്തർദേശീയ ഷിപ്പിംഗ്",
            incotermsLabel: "Incoterms",
            domesticShipping: "ആഭ്യന്തര ഷിപ്പിംഗ്",
            indiaDomestic: "ഇന്ത്യ (ആഭ്യന്തരം)",
            orderStatusDistribution: "ഓർഡർ നില വിതരണം",
            ordersOverview: "നിങ്ങളുടെ ഓർഡറുകളുടെ അവലോകനം",
            noOrderData: "ഓർഡർ ഡാറ്റ ലഭ്യമല്ല",
            procurementMetrics: "സംഭരണ മെട്രിക്സ്",
            purchasingActivity: "നിങ്ങളുടെ വാങ്ങൽ പ്രവർത്തനം",
            totalBidsReceived: "ലഭിച്ച മൊത്തം ബിഡ്ഡുകൾ",
            activeRequests: "സജീവ അഭ്യർഥനകൾ",
            costSavingsSummary: "ചെലവ് ലാഭ സംഗ്രഹം",
            procurementSavings: "നിങ്ങളുടെ സംഭരണ ലാഭം",
            potentialSavings: "സാധ്യതാ ലാഭം",
            savingsRate: "ലാഭ നിരക്ക്",
            monthlySpendingTrends: "മാസിക ചെലവ് ട്രെൻഡുകൾ",
            spendingOverTime: "കാലക്രമേണ നിങ്ങളുടെ സംഭരണ ചെലവ്",
            bidActivityTimeline: "ബിഡ് പ്രവർത്തന ടൈംലൈൻ",
            bidsPerMonth: "പ്രതിമാസം ലഭിക്കുന്ന ബിഡ്ഡുകളുടെ എണ്ണം",
        },
        seller: {
            pageTitle: "വിൽക്കുന്നവരുടെ ഡാഷ്ബോർഡ്",
            stats: {
                totalOrders: "മൊത്തം ഓർഡറുകൾ",
                pendingBids: "കാത്തിരിക്കുന്ന ബിഡ്ഡുകൾ",
                acceptedBids: "സ്വീകരിച്ച ബിഡ്ഡുകൾ",
                rejectedBids: "നിരസിച്ച ബിഡ്ഡുകൾ",
                totalRevenue: "മൊത്തം വരുമാനം",
                potentialRevenue: "സാധ്യതാ വരുമാനം",
            },
            buyerOrders: "വാങ്ങുന്നവരുടെ ഓർഡറുകൾ",
            myBids: "എന്റെ ബിഡ്ഡുകൾ",
            submitBid: "ബിഡ് സമർപ്പിക്കുക",
            updateBid: "ബിഡ് അപ്‌ഡേറ്റ് ചെയ്യുക",
            bidAmount: "ബിഡ് തുക (₹/കി.ഗ്രാം)",
            estimatedDelivery: "ഏകദേശ ഡെലിവറി തീയതി",
            pickupAddress: "പിക്കപ്പ് വിലാസം",
            message: "വാങ്ങുന്നവർക്കുള്ള സന്ദേശം",
            noBids: "ഇതുവരെ ബിഡ്ഡുകൾ സമർപ്പിച്ചിട്ടില്ല",
            noOrders: "വാങ്ങുന്നവരുടെ ഓർഡറുകൾ ലഭ്യമല്ല",
            bidSubmitted: "ബിഡ് വിജയകരമായി സമർപ്പിച്ചു",
            bidUpdated: "ബിഡ് വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു",
            analytics: "വിശകലനം",
            revenueOverview: "വരുമാന അവലോകനം",
            bidStatus: "ബിഡ് നില",
            searchOrders: "ഓർഡറുകൾ തിരയുക...",
            searchBids: "ബിഡ്ഡുകൾ തിരയുക...",
            filterStatus: "നില അനുസരിച്ച് ഫിൽറ്റർ ചെയ്യുക",
            yourBid: "നിങ്ങളുടെ ബിഡ്",
            competingBids: "മറ്റ് ബിഡ്ഡുകൾ",
            lowestBid: "ഇതുവരെ ഏറ്റവും കുറഞ്ഞ ബിഡ്",
            youAreLowest: "നിങ്ങൾ ഏറ്റവും കുറഞ്ഞ ബിഡ്ദർ ആണ്!",
            stats_ordersAvailable: "ബിഡ്ഡിനായി ലഭ്യമായ ഓർഡറുകൾ",
            stats_activeBidsPlaced: "സജീവ ബിഡ്ഡുകൾ സമർപ്പിച്ചു",
            stats_awaitingResponse: "പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു",
            stats_confirmedOrders: "സ്ഥിരീകരിച്ച ഓർഡറുകൾ",
            stats_fromAcceptedBids: "സ്വീകരിച്ച ബിഡ്ഡുകളിൽ നിന്ന്",
            newBadge: "പുതിയത്",
            liveBadge: "ലൈവ്",
            available: "ലഭ്യം",
            refreshing: "പുതുക്കുന്നു...",
            clearFilters: "ഫിൽറ്ററുകൾ മായ്ക്കുക",
            searchOrdersPlaceholder: "ഉൽപ്പന്ന പേര്, ഓർഡർ ഐഡി, അല്ലെങ്കിൽ HSN കോഡ് ഉപയോഗിച്ച് തിരയുക...",
            allCategories: "എല്ലാ വിഭാഗങ്ങളും",
            sortDateCreated: "തീയതി",
            sortTotalPrice: "മൊത്തം വില",
            sortProductName: "ഉൽപ്പന്നത്തിന്റെ പേര്",
            sortBidAmount: "ബിഡ് തുക",
            sortDeliveryDate: "ഡെലിവറി തീയതി",
            noOrdersFiltered: "നിങ്ങളുടെ ഫിൽറ്ററുകൾക്ക് അനുയോജ്യമായ ഓർഡറുകൾ കണ്ടെത്തിയില്ല.",
            newRequests: "പുതിയ അഭ്യർഥനകൾ",
            product: "ഉൽപ്പന്നം",
            hsnCode: "HSN കോഡ്",
            quality: "ഗുണമേന്മ",
            size: "വലിപ്പം",
            units: "യൂണിറ്റുകൾ",
            expectedDelivery: "പ്രതീക്ഷിക്കുന്ന ഡെലിവറി",
            pincode: "പിൻകോഡ്",
            bidRunningTill: "ബിഡ് ഇതുവരെ",
            searchBidsPlaceholder: "ഉൽപ്പന്ന പേര്, ഓർഡർ ഐഡി, അല്ലെങ്കിൽ സന്ദേശം ഉപയോഗിച്ച് തിരയുക...",
            allStatus: "എല്ലാ നിലകളും",
            deliveryDate: "ഡെലിവറി തീയതി",
            noBidsYet: "ഇതുവരെ ബിഡ്ഡുകൾ സമർപ്പിച്ചിട്ടില്ല.",
            noBidsFiltered: "നിങ്ങളുടെ ഫിൽറ്ററുകൾക്ക് അനുയോജ്യമായ ബിഡ്ഡുകൾ കണ്ടെത്തിയില്ല.",
            orderNumber: "ഓർഡർ #",
            placedOn: "സമർപ്പിച്ചത്",
            orderBudget: "ഓർഡർ ബജറ്റ്",
            qualityCondition: "ഗുണമേന്മ/അവസ്ഥ",
            analyticsOverview: "വിശകലന അവലോകനം",
            bidStatusDistribution: "ബിഡ് നില വിതരണം",
            bidOutcomesOverview: "നിങ്ങളുടെ ബിഡ് ഫലങ്ങളുടെ അവലോകനം",
            noBidData: "ബിഡ് ഡാറ്റ ലഭ്യമല്ല",
            performanceMetrics: "പ്രകടന മെട്രിക്സ്",
            overallSuccessRate: "നിങ്ങളുടെ മൊത്തം വിജയ നിരക്ക്",
            bidSuccessRate: "ബിഡ് വിജയ നിരക്ക്",
            totalBids: "മൊത്തം ബിഡ്ഡുകൾ",
            totalValue: "മൊത്തം മൂല്യം",
            revenueSummary: "വരുമാന സംഗ്രഹം",
            earningsOverview: "നിങ്ങളുടെ വരുമാന അവലോകനം",
            totalPotential: "മൊത്തം സാധ്യത",
            confirmedRevenue: "സ്ഥിരീകരിച്ച വരുമാനം",
            avgBidValue: "ശ.ശ. ബിഡ് മൂല്യം",
            monthlyRevenueTrends: "മാസിക വരുമാന ട്രെൻഡുകൾ",
            earningsOverTime: "സ്വീകരിച്ച ബിഡ്ഡുകളിൽ നിന്ന് നിങ്ങളുടെ വരുമാനം",
            acceptedRevenue: "സ്വീകൃത വരുമാനം",
            totalBidValueLabel: "മൊത്തം ബിഡ് മൂല്യം",
            last7DaysActivity: "കഴിഞ്ഞ 7 ദിവസത്തെ പ്രവർത്തനം",
            recentBiddingActivity: "നിങ്ങളുടെ സമീപകാല ബിഡ്ഡിംഗ് പ്രവർത്തനം",
            onlyBidder: "നിങ്ങൾ മാത്രം ബിഡ്ദർ!",
            leading: "മുൻനിലയിൽ",
            onlyBidderMessage: "നിങ്ങളുടെ ബിഡ് ഈ ഓർഡറിനുള്ള ഏകമാത്ര ഓഫറാണ്. ജയിക്കാൻ ഉയർന്ന സാധ്യതയുണ്ട്!",
            rank: "റാങ്ക്",
            bestPriceLabel: "ഏറ്റവും കുറഞ്ഞ വില",
            highestPriceLabel: "ഏറ്റവും ഉയർന്ന വില",
            youHaveLowestBid: "നിങ്ങൾക്ക് ഏറ്റവും കുറഞ്ഞ ബിഡ് ഉണ്ട്",
            veryCompetitive: "വളരെ മത്സരാത്മകം",
            competitive: "മത്സരാത്മകം",
            highPrice: "ഉയർന്ന വില",
            loadMore: "കൂടുതൽ ലോഡ് ചെയ്യുക",
            more: "കൂടുതൽ",
            enquiryNumber: "അന്വേഷണ നമ്പർ",
            loadingDashboard: "ഡാഷ്ബോർഡ് ലോഡ് ചെയ്യുന്നു...",
            bidCount: "ബിഡ്ഡുകൾ",
            enterBidAmount: "നിങ്ങളുടെ ബിഡ് തുക നൽകുക",
            orderBudgetLabel: "ഓർഡർ ബജറ്റ്:",
            personalizedMessage: "നിങ്ങളുടെ സാധ്യതകൾ വർദ്ധിപ്പിക്കാൻ ഒരു വ്യക്തിഗത സന്ദേശം ചേർക്കുക...",
            otherSeller: "മറ്റ് വിൽക്കുന്നയാൾ",
            otherSellers: "മറ്റ് വിൽക്കുന്നവർ",
            reduceByApprox: "ഏറ്റവും കുറഞ്ഞതിനോട് മേൽക്കൊള്ളാൻ ഏകദേശം",
            toMatchBest: "കുറയ്ക്കുക",
            onlyWord: "മാത്രം",
            aboveLowest: "ഏറ്റവും കുറഞ്ഞതിൽ നിന്ന് മേലെ",
            higherThanLowest: "ഏറ്റവും കുറഞ്ഞതിനേക്കാൾ കൂടുതൽ",
            bidsLabel: "ബിഡ്ഡുകൾ:",
            valueLabel: "മൂല്യം:",
            bidAcceptedStatus: "ബിഡ് സ്വീകരിച്ചു",
            bidRejectedStatus: "ബിഡ് നിരസിച്ചു",
            loginToPlaceBid: "ബിഡ് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക.",
            selectOrderToBid: "ബിഡ് ചെയ്യാൻ ഒരു ഓർഡർ തിരഞ്ഞെടുക്കുക.",
            noBidSelectedForEdit: "എഡിറ്റിംഗിന് ഒരു ബിഡ് തിരഞ്ഞെടുത്തിട്ടില്ല.",
            fillBidAmountDelivery: "ബിഡ് തുകയും ഡെലിവറി തീയതിയും പൂരിപ്പിക്കുക.",
            enterValidBidAmount: "ശരിയായ ബിഡ് തുക നൽകുക.",
            bidSubmittedDescription: "നിങ്ങളുടെ ബിഡ് വിജയകരമായി സമർപ്പിച്ചു.",
            bidUpdatedDescription: "നിങ്ങളുടെ ബിഡ് വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു.",
            failedCreateBid: "ബിഡ് സൃഷ്ടിക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക.",
            failedUpdateBid: "ബിഡ് അപ്‌ഡേറ്റ് ചെയ്യാനായില്ല. വീണ്ടും ശ്രമിക്കുക.",
        },
        admin: {
            pageTitle: "അഡ്മിൻ ഡാഷ്ബോർഡ്",
            stats: {
                totalItems: "മൊത്തം ഉൽപ്പന്നങ്ങൾ",
                totalOrders: "മൊത്തം ഓർഡറുകൾ",
                totalBids: "മൊത്തം ബിഡ്ഡുകൾ",
                totalUsers: "മൊത്തം ഉപയോക്താക്കൾ",
                activeItems: "സജീവ ഉൽപ്പന്നങ്ങൾ",
                pendingOrders: "കാത്തിരിക്കുന്ന ഓർഡറുകൾ",
                totalRevenue: "മൊത്തം വരുമാനം",
            },
            addItem: "ഉൽപ്പന്നം ചേർക്കുക",
            editItem: "ഉൽപ്പന്നം എഡിറ്റ് ചെയ്യുക",
            deleteItem: "ഉൽപ്പന്നം ഇല്ലാതാക്കുക",
            addSeller: "വിൽക്കുന്നയാളെ ചേർക്കുക",
            manageItems: "ഉൽപ്പന്ന മാനേജ്‌മെന്റ്",
            manageOrders: "ഓർഡർ മാനേജ്‌മെന്റ്",
            manageUsers: "ഉപയോക്താക്കൾ",
            confirmDelete: "ഈ ഉൽപ്പന്നം ഇല്ലാതാക്കണമോ?",
            itemName: "ഉൽപ്പന്നത്തിന്റെ പേര്",
            itemDescription: "വിവരണം",
            itemPrice: "വില",
            itemCategory: "വിഭാഗം",
            itemQuantity: "അളവ്",
            itemCondition: "അവസ്ഥ",
            specifications: "സ്പെസിഫിക്കേഷനുകൾ",
            addSpec: "സ്പെസിഫിക്കേഷൻ ചേർക്കുക",
            sellerEmail: "വിൽക്കുന്നയാളുടെ ഇമെയിൽ",
            sellerName: "വിൽക്കുന്നയാളുടെ പേര്",
            sellerPassword: "പാസ്‌വേഡ്",
            createSellerAccount: "വിൽക്കുന്നയാളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക",
        },
        shipping: {
            pageTitle: "ഷിപ്പിംഗ് ദാതാവ് ഡാഷ്ബോർഡ്",
            stats: {
                totalOrders: "ലഭ്യമായ ഓർഡറുകൾ",
                pendingBids: "കാത്തിരിക്കുന്ന ബിഡ്ഡുകൾ",
                acceptedBids: "സ്വീകരിച്ച ബിഡ്ഡുകൾ",
                rejectedBids: "നിരസിച്ച ബിഡ്ഡുകൾ",
                potentialRevenue: "സാധ്യതാ വരുമാനം",
                totalBidValue: "മൊത്തം ബിഡ് മൂല്യം",
            },
            availableOrders: "ലഭ്യമായ ഓർഡറുകൾ",
            myBids: "എന്റെ ഷിപ്പിംഗ് ബിഡ്ഡുകൾ",
            submitBid: "ബിഡ് സമർപ്പിക്കുക",
            updateBid: "ബിഡ് അപ്‌ഡേറ്റ് ചെയ്യുക",
            bidAmount: "ബിഡ് തുക (₹)",
            estimatedDelivery: "ഏകദേശ ഡെലിവറി തീയതി",
            message: "സന്ദേശം",
            noBids: "ഇതുവരെ ഷിപ്പിംഗ് ബിഡ്ഡുകൾ സമർപ്പിച്ചിട്ടില്ല",
            noOrders: "ഷിപ്പിംഗിനായി ഓർഡറുകൾ ലഭ്യമല്ല",
            bidSubmitted: "ഷിപ്പിംഗ് ബിഡ് സമർപ്പിച്ചു",
            bidUpdated: "ഷിപ്പിംഗ് ബിഡ് അപ്‌ഡേറ്റ് ചെയ്തു",
            pickupAddress: "പിക്കപ്പ് വിലാസം",
            deliveryAddress: "ഡെലിവറി വിലാസം",
            distance: "ദൂരം",
            analytics: "വിശകലനം",
        },
        cardamom: {
            pageTitle: "ഏലം മാർക്കറ്റ് വില",
            liveData: "തൽസമയ മാർക്കറ്റ് ഡാറ്റ",
            lastUpdated: "അവസാനം അപ്‌ഡേറ്റ് ചെയ്തത്",
            grade: "ഗ്രേഡ്",
            minPrice: "കുറഞ്ഞ വില",
            maxPrice: "ഉയർന്ന വില",
            modalPrice: "മോഡൽ വില",
            market: "മാർക്കറ്റ്",
            commodity: "ചരക്ക്",
            variety: "ഇനം",
            noData: "വില ഡാറ്റ ലഭ്യമല്ല",
            refreshData: "ഡാറ്റ പുതുക്കുക",
            lastUpdatedPrefix: "അവസാനം അപ്‌ഡേറ്റ് ചെയ്തത്:",
            priceHistoryTitle: "വില ചരിത്രം (കഴിഞ്ഞ 10 ദിവസം)",
            priceHistoryDesc: "ശരാശരി ഏലം മോഡൽ വില ട്രെൻഡ്",
            modalPriceLabel: "മോഡൽ വില (₹/കി.ഗ്രാം)",
            visitMarketPrices: "ഡാറ്റ ലോഡ് ചെയ്യാൻ മാർക്കറ്റ് വില പേജ് സന്ദർശിക്കുക",
            todaysPrices: "ഇന്നത്തെ വില",
            latestAvailablePrices: "ഏറ്റവും പുതിയ ഏലം വില",
            avgPrice: "ശ.ശ.",
            noPricesToday: "ഇന്ന് വിലകൾ ഇല്ല",
            refreshMarketData: "മാർക്കറ്റ് ഡാറ്റ പുതുക്കുക",
            viewAll: "എല്ലാം കാണുക",
        },
        rfq: {
            pageTitle: "ആർഎഫ്ക്യു മാനേജ്‌മെന്റ്",
            createRFQ: "പുതിയ ആർഎഫ്ക്യു സൃഷ്ടിക്കുക",
            myRFQs: "എന്റെ ആർഎഫ്ക്യുകൾ",
            totalRFQs: "മൊത്തം ആർഎഫ്ക്യുകൾ",
            openRFQs: "തുറന്ന ആർഎഫ്ക്യുകൾ",
            awarded: "അവാർഡ് ചെയ്തത്",
            totalQuotes: "മൊത്തം ക്വോട്ടുകൾ",
            rfqTitle: "ആർഎഫ്ക്യു തലക്കെട്ട്",
            rfqDescription: "വിശദാംശം",
            deadline: "സമയ പരിധി",
            viewDetails: "വിശദാംശങ്ങൾ കാണുക",
            noRFQs: "ആർഎഫ്ക്യുകൾ ഇല്ല",
            manageQuotes: "നിങ്ങളുടെ ക്വോട്ട് അഭ്യർഥനകൾ നിയന്ത്രിക്കുക",
        },
        market: {
            pageTitle: "മാർക്കറ്റ് വില",
            liveUpdates: "തൽസമയ അപ്‌ഡേറ്റ്",
            historicalData: "ചരിത്ര ഡാറ്റ",
        },
    },
};
